# Exploration of datasets

In [19]:
import os, sys
from nltk.stem.snowball import SnowballStemmer
import numpy as np
import pandas as pd
from pathlib import Path

sys.path.append(os.path.abspath(".."))
from genai_detection.detectors.impostor import ImpostorDetector
from genai_detection.visualization import datasets
from config import CONFIG
from functools import partial
import gc
import datetime
import textwrap
import pyreadstat

In [20]:
def print_min_len_text_sample(df):
    df["text_length"] = df["pair"].apply(
        lambda x: min(len(x[0].split()), len(x[1].split()))
    )
    min_len_texts = df[df["text_length"] == min(df["text_length"])]
    shorter_text = min(min_len_texts["pair"].values[0], key=lambda t: len(t.split()))
    print(
        f"Text with minimal length {len(shorter_text.split())}:\n{textwrap.fill(shorter_text, width=100)}\n"
    )


def print_max_len_text_sample(df):
    df["text_length"] = df["pair"].apply(
        lambda x: min(len(x[0].split()), len(x[1].split()))
    )
    max_len_texts = df[df["text_length"] == max(df["text_length"])]
    longer_text = max(max_len_texts["pair"].values[0], key=lambda t: len(t.split()))
    print(
        f"Text with maximal length {len(longer_text.split())}:\n{textwrap.fill(longer_text, width=100)}"
    )

# Student Essay Dataset

In [21]:
path2student_essays = (
    Path(os.getcwd()).resolve().parent / CONFIG.DATA_BASE_PATH / "student_essays/"
)
assert (
    path2student_essays.exists()
), f"Path {path2student_essays} to student essays dataset does not exist."
sav_files = list(path2student_essays.rglob("*.sav"))
assert len(sav_files) > 0, f"No .sav files found in {path2student_essays}."
for file in sav_files:
    assert file.exists(), f"File {file} does not exist."
    # print(f"\n=== {file.name} ===")
    df, meta = pyreadstat.read_sav(file, apply_value_formats=True, metadataonly=False)
    # display(df)   # Uncomment to display the dataframe in Jupyter Notebook, do not commit because sensitive data

In [22]:
import chardet

# build student essays dataset
student_essays_df = pd.DataFrame(
    columns=["author_id", "text", "task", "task_description"]
)
task_description = {
    "Ass1": "Stream of consciousness",
    "Ass2": "Talk about your childhood",
    "Ass3": "Describe your personality",
    "Ass4": "Thematic Apperception Test",
    "Ass5": "Give four examples of four different theories",
}
# iterate over all TXT files in assignment directories and extract the essays
for dir in [f"Ass{i}" for i in range(1, 6)]:
    path2ass_dir = (
        Path(os.getcwd()).resolve().parent
        / CONFIG.DATA_BASE_PATH
        / "student_essays/Intro2006"
        / dir
    )
    assert (
        path2ass_dir.exists()
    ), f'Path {path2ass_dir} to Assignment "{task_description[dir]}" of student essays dataset does not exist.'

    if dir == "Ass5":  # has subtasks (directories)
        text_files = []
        for subtask in path2ass_dir.iterdir():
            text_files.extend(subtask.glob("*.txt"))
    else:
        text_files = path2ass_dir.glob("*.txt")

    for txt_file in text_files:
        with open(txt_file, "rb") as f:
            raw_data = f.read()
            detected = chardet.detect(raw_data)
            encoding = detected["encoding"]

        essay_text = raw_data.decode(encoding)
        student_essays_df = pd.concat(
            [
                student_essays_df,
                pd.DataFrame(
                    [
                        {
                            "author_id": txt_file.stem,
                            "text": essay_text,
                            "task": txt_file.parent.name,
                            "task_description": task_description[dir],
                        }
                    ]
                ),
            ]
        )

display(student_essays_df)

# metadata dataframe
author_metadata_columns = [
    "ID",
    "TEACHER",
    "BIRTHORD",
    "SEX",
    "ETHNIC",
    "POLITOR",
    "YEAR",
]
rename_map = {
    "ID": "author_id",
    "TEACHER": "teacher",
    "BIRTHORD": "birthorder",
    "SEX": "sex",
    "ETHNIC": "ethnicity",
    "POLITOR": "political_orientation",
    "YEAR": "year",
}
raw_metadata, _ = pyreadstat.read_sav(
    Path(os.getcwd()).resolve().parent
    / CONFIG.DATA_BASE_PATH
    / "student_essays/Intro2006/2006Big5xxx.sav",
    apply_value_formats=True,
    metadataonly=False,
)
available_columns = [
    col for col in raw_metadata.columns if col in author_metadata_columns
]
author_metadata = raw_metadata[available_columns].copy()
author_metadata.rename(columns=rename_map, inplace=True)
# keep NaNs, no answer is also an answer group
display(author_metadata)

,author_id,text,task,task_description
0,2006_EFB232,I come from a small town on the coast of Texas...,Ass1,Stream of consciousness
0,2006_VBC75,"Alright, so the first thought in my head is wo...",Ass1,Stream of consciousness
0,2006_SMY244,I don't know why this kind of stuff always hap...,Ass1,Stream of consciousness
0,2006_MM22236,I feel very full at the present time. I had no...,Ass1,Stream of consciousness
0,2006_AUSTINKW,My name is Kyle Austin and my EID is austinkw....,Ass1,Stream of consciousness
...,...,...,...,...
0,JWJ296,My stepmother is extremely prone to committing...,Ass5a,Give four examples of four different theories
0,JDP2276,An example of the fundamental attribution erro...,Ass5a,Give four examples of four different theories
0,CEG588,The only thing I can think of that relates to ...,Ass5a,Give four examples of four different theories
0,KAM2437,Every once in a while I would run into a girl ...,Ass5a,Give four examples of four different theories
0,RAM2442,I think in highschool I was kind of bitchy aro...,Ass5a,Give four examples of four different theories

,author_id,teacher,sex,ethnicity,birthorder,political_orientation,year
0,144332,Gosling,female,Hispanic,oldest,middle,2.0
1,AA8763,Pennebaker,male,other,oldest,NaN,1.0
2,AAA958,Gosling,female,Hispanic,oldest,middle,1.0
3,AAH683,Pennebaker,male,Asian Amer,second,ext cons,1.0
4,AAH699,Pennebaker,female,Asian Amer,oldest,middle,1.0
...,...,...,...,...,...,...,...
1042,ZH523,Pennebaker,male,Asian Amer,oldest,som lib,3.0
1043,ZL374,Gosling,female,Hispanic,oldest,som lib,2.0
1044,ZLL62,Pennebaker,male,Asian Amer,oldest,ext lib,1.0
1045,ZRP68,Gosling,male,White,oldest,som cons,1.0
1046,ZWS73,Pennebaker,NaN,NaN,NaN,NaN,NaN

In [23]:
# display(student_essays_df[student_essays_df.task=="Ass5a"] )
# display(student_essays_df[student_essays_df.task=="Ass5b"] )
# display(student_essays_df[student_essays_df.task=="Ass5c"] )
# display(student_essays_df[student_essays_df.task=="Ass5d"] )

In [24]:
student_essays = datasets.StudentEssaysVisualization()
ds_student_essays = student_essays.load_dataset()
labels_student_essays = ds_student_essays["same"]
display(ds_student_essays.head())

                                                pair             authors  same
0  [i am a person who likes to be hugged. i like ...    [SNJ244, SNJ244]  True
1  [my name is noel wat. i am a girl. i am chines...      [NHW87, NHW87]  True
2  [it takes most people a lot to find out the re...  [AMM2237, AMM2237]  True
3  [loyal, confident, shy, peformer, stubborn, in...    [MNM432, MNM432]  True
4  [a younger lady, possibly a student is putting...    [DPL253, DPL253]  True

In [25]:
student_essays_stats = student_essays.dataset_stats()

Display texts of minimal and maximal length from the student essay dataset.

The shortest Student Essay text (500 words) is a (fictional) story about theft of experiment results with a happy ending.

In [27]:
print_min_len_text_sample(ds_student_essays)

Text with minimal length 500:
there are a lot of things going on in a laboratory. not all of it deals with experiments and
research. in the picture, dr joanne and smith and seen together. dr joanne had the opportunity to do
a highly selective study on the disease effecting the bodies of small puppies. she was picked from
many scientists, including dr smith. the two women have gone to school together for their whole
lives, and the they'v also been best friends from day one. although they are friends, they're
secretely competitive with each other. therefore, when dr joanne was selected to perform the
research, dr smith was extremely sad. dr smith has been scheming a plan to ruin dr joanne's
experiment. she's been coming with dr joanne to work everyday so she can examine what she does,
where everything is, and all of joanne's lab data. her plan is to take the lab notes that she's done
with, keep them, and replace them with her made up notes that are truly obsurd. dr smith has been
pretending to help dr joanne figure out a cure for the disease, but she's just learning about her
discoveries to backstab her at the end. the experiment was successful for about 2 months, until one
day when dr joanne came into the lab and saw that all of her things we stolen, and mainly her notes.
dr smith was suddenly out of town that day also. dr joanne had called dr smith crying, and she was
extremely worried about what the experiment head executives would say about their fundings for the
experiment. as the day passed by, dr joanne was trying to recover her items, and she had seen dr
smith's wallet by her data table where everything was missing. she was a bit suspicious of her
friends, but thought nothing more of it. about a month later, dr joanne was starting to recover her
discoveries of the disease, and suddenly she saw on the news, her best friend, dr smith. smith was
being rewarded the science prize of achievement for finding the first anecdote for the small puppy
disease, dziteriza, that dr joanne was working on. her heart dropped when she heard all of the
experiments that she had performed coming from smith's mouth. she never thought that her friend
would possibly backstab her in such a way. in tears, dr joanne had called her husband to tell him
about the news. coincidently, her husband was with dr smith. dr joanne could not understand what was
happening. it was like she had lost her best friend and her husband. it turns out that dr smith was
working with dr joanne's husband all this time to sneak out the data and steal her equipment.
they've been having a secret affair since the night befor dr joanne and her husband's wedding. in
the end, dr joanne had a divorce with her husband, dr smith was discovered as a fraud, and dr joanne
was given credit for her experiment.

The longest Student Essay text (1136 words) is a text about the inner thoughts of a person who seems to think he is manipulative and hurts women without them knowing it after a breakup.

In [28]:
print_max_len_text_sample(ds_student_essays)

Text with maximal length 1136:
as many people as there are in the world, there probably isn't any one specific thing that is unique
about me. however, the range and variety of my composition probably is unique. i think of myself as
a sort of jumbled mess that i'm trying to sort out, clean up and destroy. i -- the ego within me --
is the secretary for a mega-introvert. it's difficult for me to explain myself because i don't
really know exactly what i am. i've been sifting through the pieces for so long that i can tell you
what i possess, but i can't tell you how long i will keep any given piece, or what pieces will be
added on. i'm a shape-shifter, a chameleon, a transformer. and i'm not even referring to the
transition from high school to college. my freshman year i was silent and a lone wolf. my senior
year i was homecoming king. i've gone through almost every phase a person can go through. that's one
thing that is not unique to me (i know at least one person who is the same way -- my father), but is
probably pretty rare. i become infatuated with things to the point that i most know everything about
them, and the moment i feel that i have reached that goal, i stop and return to homeostasis. that's
probably part of the reason i've changed so much so often. i don't even know if other people realize
the transformations, but i do. maybe it's because they don't know me as well as i do, and they don't
hear the utterings of my mind. but then again, those are probably the only things that don't really
change about me during my mutations, aside from physical features. i'm proud of my ability to
create, but disappointed in my inability to share. if i could create my own words, i would have no
trouble sharing myself. but if i did that people would think i was crazy. i already do half the
time, and if anyone else agreed, i'd have to institutionalize myself. i really don't think there's
much to say about my childhood, except that i was encouraged to be open and honest, and i learned to
be tactful from one of the most skilled communicators i've ever met -- my mom. i've realized from my
time in college that i can manipulate people like no one else, even when intoxicated. that's one of
the many things i've been analyzing, trying to decide if i want it to be a part of my identity. to
what extent am i allowed to manipulate people for my own entertainment? do i have the right to be
mad at them if they manipulate me? that sort of thing. i think a big part of my self-discovery took
place this summer working for my brother-in-law at his bar in san antonio. i had never even been
around alcohol, so it was a very new experience for me to suddenly be distributing it to people. i
watched my brother-in-law and figured out what aspects of his personality i liked, and i began to
adopt them. i witnessed for the first time that there was a way to be the alpha male type without
coming off as aggressive, intimidating, or like the alpha male type. he's the kind of guy that you
don't mess with, but he's so cool that you never need to. and he's probably the only person i know
who could compete with my mom in the communication department. he said when you work at a bar you
have to learn to manipulate people (from calming them down to exciting them into buying more
drinks). one of my deepest beliefs is to be real and true to myself. that's a big reason why i made
the transition from die- hard christian to weak atheist my senior year. i realized that there were
more questions than answers, and the answers were never sufficient. my faith was based on circular
arguments, question begging, and false hope with no grounds in reality. i have a lot of resentment
for the men who go around campus spouting their christian bullshit on our ears, knowing that they
would condemn me to hell in an instant if they knew how i felt, when all i want from this is to be
free of their oppression and condescension. the majority are so closed-minded and cowardly that they
are completely unwilling to face reality. it's sad to me that so many people rely on religious
sunglasses to help them through life. i do believe that i am a stronger person than many of them
because i've learned to deal with issues alone or with the help of friends and not some invisible
father-figure from a book and my imagination. anyways... the biggest psychological issue for me is
definitely the breakup i underwent midway through my senior year. i was a good guy who always
treated girls right, and i met the girl who i truly believed (and still do) could be my wife. i
loved her, we spent every moment together, we lost our virginity to each other... then out of
nowhere she spooked. i really think that her parents' divorce instilled a fear of commitment in her.
anyway, we've drifted apart now and we speak once a week. a part of me hates her for what she did to
me, and a part of me still loves her. the biggest result i've noticed is that i've stopped viewing
girls as individuals and more as a group to be exploited. i've done things to girls in the past
months that i would have never done to a girl before that breakup. i think i lost almost all trust
for women when we broke up, and since i never allowed myself to let all of my rage out on her, now
it's slowly trickling out on every other girl. i still will not let that rage out, because 1) i care
about her and 2) i have to be a man and keep that inside, or at least out of her sight. so now i'm
basically a player-in-training. i don't know how long it will last, but i really don't feel the need
to destroy it yet. i still have to much hatred inside of me. at least no one has gotten hurt yet, or
at least not to my knowledge. i'm pretty tactful about it all, so i don't think the girls ever
really know what's going on. they all think they're my one and only, that sort of thing. i know it's
wrong, so does that still make me a terrible person? i don't know, and frankly, i don't care right
now. maybe that makes me a terrible person.

In [29]:
# ds_student_essays["text_length"] = ds_student_essays["pair"].apply(lambda x: min(len(x[0].split()), len(x[1].split())))
# min_len_texts = ds_student_essays[ds_student_essays["text_length"] == min(ds_student_essays["text_length"])]
# shorter_text = min(min_len_texts['pair'].values[0], key=lambda t: len(t.split()))
# # print(f"Text with minimal length {len(shorter_text.split())}:\n{textwrap.fill(shorter_text, width=100)}\n")

# max_len_texts = ds_student_essays[ds_student_essays["text_length"] == max(ds_student_essays["text_length"])]
# longer_text = max(max_len_texts['pair'].values[0], key=lambda t: len(t.split()))
# print(f"Text with maximal length {len(longer_text.split())}:\n{textwrap.fill(longer_text, width=100)}")

In [30]:
del student_essays
del ds_student_essays
gc.collect()

465

## PAN 2023

In [31]:
# pan23 = datasets.Pan23Visualization()
# ds_pan = pan23.load_dataset()
# labels = ds_pan['same']
# display(ds_pan.head())

In [32]:
# labels.value_counts()

In [33]:
# pan23_stats = pan23.dataset_stats()

In [34]:
# pan23.plot_avg_text_length_per_author()
# pan23.plot_text_length_histogram(bins=50)
# pan23.boxplots_text_len_ngrams()

# # Python garbage collector to release memory
# del pan23
# gc.collect()

## PAN 20

In [35]:
pan20 = datasets.Pan20Visualization()
ds_pan20 = pan20.load_dataset()
labels_pan20 = ds_pan20["same"]
display(ds_pan20.head())

,id,fandoms,pair,same,authors
0,6cced668-6e51-5212-873c-717f2bc91ce6,"[Guardians of Ga'Hoole, Hetalia - Axis Powers]","[i shift a bit, warily letting my eyes dart fr...",True,"[1446633, 1446633]"
1,3c6c188a-db28-59aa-8c09-3d0f799ff579,"[Guardians of Ga'Hoole, Warriors]","[i shift a bit, warily letting my eyes dart fr...",True,"[1446633, 1446633]"
2,b0cfa94f-c9ec-5aa5-8331-a5a249b664cf,"[Guardians of Ga'Hoole, Xiaolin Showdown]",[a single tear escaped me as i left. i did hav...,True,"[1446633, 1446633]"
3,e6e86e73-9a7b-58f2-a652-a17b4a1bcabf,"[Hetalia - Axis Powers, Warriors]","[""ja."" ludwig kept his gaze upon her, solidly....",True,"[1446633, 1446633]"
4,4fe541af-912e-5a86-81a5-94c6d3891509,"[Hetalia - Axis Powers, Xiaolin Showdown]","[and he did. slowly, hesitantly...but coming f...",True,"[1446633, 1446633]"

The shortest PAN20 text (505 words) does not really make sense.

In [36]:
print_min_len_text_sample(ds_pan20)

Text with minimal length 505:
.  olympias       .        .          .               philip.      .            philip, pausanias.
pausanias            philip. ,               philip      pausanias.      olympias     euridice.
euridice   philip   .      phillip, olympias             . ,  euridice      .  olympias
euridice   .  , euridice             olympias.  , olympias  euridice                   .  olympias
.  , olympias       antipater  .         olympias   philip.          .             " .
.          .   , cassander,    ,  olympias.                .  olympias               .
",    philip.         , , ,  .  olympias                  .  olympias                      .  philip
,  olympias             .  philip      heracles,    hercules,  olympias       helen          iliad
.  iliad       .         , ,                .           . ,    , olympias          ,      :  zeus.
,           ,     ,    .       ,              .  ,           .   seer  siwa,      zeus ,  ,
.                        .            .           ,        . ,                      ,  ,   .
,         ,        .            .       ,                  .            .  philip     ,      .
.      bucephalus, -  ,           bucephalus             hydapses.          .     bucephalus .
uxia,    bucephalus       ,      ,     .               bucephalus    .  bucephalus  .       ,
bucephalus   ,       bucephalus    , bucephala,   .          craterus,           .    craterus  --
,       .                .        ,                 persians.       ,    .       craterus
.  craterus           .   amastrine,   oxyatres,         , darius.     craterus         .
cleitus  .  cleitus       philip.    cleitus           .      philip    ,    , lanice,     .  lanice
. cleitus            philip              granicus. ,    cleitus   philip        .
cleitus bactria,       . cleitus,                ,           .        cleitus        : philip.
cleitus      philip                   .             ,        .       cleitus    ,        , cleitus
.            cleitus.                 .   ,      .          ,             .     cleitus      .
,          cleitus   cleitus          . , cleitus        .         .  ptolemy  ,         -
philip.  ,   .           .       ptolemy           macedon.               .  ptolemy    pharaoh
ptolemaic.             .               . ,                .    philotas.  philotas         ,
parmenio,       .                , philotas     .              .      .             .  philotas
,       ,        .    .       .  ,             .         philotas  ecbatana ,            ,
philotas        .       parmenio  ,        .  cassander              deceitful  .  cassander
antipitar  .           .     .  cassander         ,            .  cassander      ,         .
cassander      .     antipater    cassander     .      , ,     ,                .  cassander
babylon         .                     iollas.             .         cassander.    cassander
.  cassander        .       , olympias,       , roxanne,   ,  iv.        ,        ,   .
- - .       297 ..                      ,           .      .   ,   ,                    .  bagoas
, darius.   darius        issus         ,  bagoas.  bagoas    darius ,       ,     .
bagoas   ,           .  bagoas             .         , bagoas       .  bagoas           .     .
roxane.    --     oxyartes.                  .      ,              .              .          ,
.               .    roxane     .        .       roxane           "    .  roxane         .
, olympias.  roxane         cunning            .       , roxane         iv.           , roxane
.       parysatis,      . ,    roxane     , stateira,   darius,    , drypetis,  .        .  roxane
olympias.         philip,    -- ,  .     ,  .  cassander  roxane          .       --,  ,    .
,    .                     , hephaestion.  hephaestion         .         .      ,     , hephaestion
.                      .  philip  olympias        .        ,        .    ,        .       ,
hephaestion.    hephaestion     .         patroclus  iliad  .       .     iliad       ,
.          patroclus    .                -.            .        hephaestion         .      ,
.     ,            hephaestion   patroclus.              hephaestion      patroclus.               .
hephaestion,              ,     persians.   darius     issus,    hephaestion        darius.   ,
sisygambis,  hephaestion                     .            . ,       ,            ,     .    ,
,     hephaestion    .    hephaestion         .         ,          .                   .           ,
.                    .   ,             .    hephaestion, ,        .            .
hephaestion.                   .    hephaestion, chilliarch,           .           .  hephaestion
.           .             hephaestion.         hephaestion          .  hephaestion  craterus
,  hephaestion   .   drypetis,      stateira  .               ,        .  hephaestion          ,
,    .      hephaestion     ,         hephaestion ,   .

The longest PAN20 text (55,406 words) seems to be a book with multiple chapters.

In [37]:
print_max_len_text_sample(ds_pan20)

Text with maximal length 55406:
chapter 1 the sun had risen on their last day in the port of sinjai, the final destination before
returning to basra with the sultan omar"s supplies. there would be a late tide so sinbad gave shore
leave to all but himself and 3 members of the crew with orders to have fun but return in shape to
weigh anchor at the evening"s high tide. firouz decided to remain on board as well. he had been
working on some experiments that needed his undivided attention. garret was in charge of the cargo.
he had to itemize the sultan"s wares. the other two crewmen were young and wet behind the ears. they
had come aboard in basra and were too excited to be a part of sinbad"s crew to care about shore
leave. they had offered to help garret in exchange for some sparring against the captain"s sword.
sinbad had learned to fight in a similar manner and in fact, was honored that they felt his skills
where worth losing a day of shore leave. unlike sinbad however, who was new at the art of fencing
the first time he boarded a ship, these young, aspiring sailors had wielded swords for at least 5
years as he figured and just wanted to see if the stories of sinbad skills were myth. still it
doesn"t hurt to know your crew"s abilities. a sword is not a required tool of the sea but as of late
it was convenient. ji was native born to basra. well-meaning, he was often clumsy and easily
disoriented in his work. sinbad found his swordsmanship was no different. but ruadh was as different
with his use of a sword as he was in his looks. ruadh was celtic by birth. like sinbad, his father
was a merchant sailor, often toting his family around like cargo to the next port and like doubar
was abandoned to raise a little brother by the curse of an ill wind. maybe that was why he had
agreed to take the two young whelps, as omar referred to them, on this trip. he remembered seeing
ruadh"s little red-headed brother on the docks just as they set sail. omar had him tucked under his
arm kicking and screaming that he was not old enough to sail with sinbad. why, he wondered, was it
such a big thing to be aboard a ship with the likes of him. after all he was just a simple sailor.
sinbad stripped out of his shirt. in the first five minutes of the fight he had found ruadh"s
weakness and made plans to use it. ruadh"s temper was as quick as his sword and hot as the sun. used
to his advantage, sinbad"s opponent would yield in a matter of minutes. still, history has proven
that many an opponent has fallen to a mighty sword wielded in anger. but once sinbad raised the
boy"s ire, ruadh would most likely be unaware of his action. it would stop being a sparring match
and become a fight for his life. he knew from experience that once he peaked the lad"s anger the
young man would be out of control. it was that temper if unharnessed, that would be the lad"s
downfall. if sinbad could teach him to control that temper and use its heat in battle, it would make
the lad"s sword unstoppable. the sound of clashing metal echoed off the cliffs. sinbad had barely
broken into a sweat when he laughed. "it"s been a long time since i sparred with such a worthy
opponent." the young captain smiled. "yeah?" ruadh beamed, "i was the best in all my clan."
"really?" sinbad returned sarcastically. "aye!" ruadh was at once unsure if the captain was dealing
with him seriously. "really! i believe you," sinbad quipped "so was she!" garret, sinbad and ji
nearly burst their sides laughing. ruadh"s face turned as red as his hair and, just as sinbad
predicted, his young opponent lost control. "the first thing you should remember," sinbad lectured,
blocking blow after wild blow, " is that if you lose control of your temper, you lose control of
your sword." the young man looked like a man possessed, growling and screaming, becoming more
agitated with every block and parry. "and in that case," he continued, "there is only...one....
alternative, and that"s....." and with that, he slammed the kid"s sword out of his hand and tossed
him overboard. panting, he stared down at the stunned and soaked teen and finished.... "cool off!"
it was then sinbad noticed the longboat approaching. it was not theirs and he didn"t see another
ship in sight. with 10 men at her oars, ruadh barely had time to board before the craft was ship-
side. "ahoy mate! i look for the captain of this fine vessel the nomad." bellowed a fearsome looking
man. "in that case," sinbad announced, "you have found him." "you? you are but a child." he laughed.
sinbad just smiled. this man was trying to toy with him. "nonetheless, i am sinbad, captain of the
nomad." suddenly he felt the ship pull beneath them. someone was boarding from the other side.
sinbad used his sword to cut away the cargo net and hollered back to garret to repel boarders.
firouz had just come above when he heard sinbad"s command. he drew his sword and started to cut away
the nets on the other side of the ship, but it was already too late. the crew of at least one of the
two other longboats had boarded, but he would hinder any other attempt. he turned to see garret take
a dirk in the shoulder and fall into the cargo hold, and ji was being held with a knife to his
throat. "captain ...i believe i have you at a disadvantage...drop you sword or he dies!" sinbad
nodded to the others who lowered their arms and sinbad placed his sword at the foot of their captor.
"now release the boy!" he demanded. the others pirates finally boarded. they were now out-numbered 8
to 1 with little or no hope that the nomad"s own crew would return to rescue them for hours yet.
"you make no demands of me boy. i believe i hold all the cards, dear captain." the man said as he
pressed his blade to the boy"s throat. it was all sinbad could do to keep ruadh from charging the
man. "where is the rest of your crew, sinbad? more importantly, where might i find the one called
doubar?" "what do you want with doubar?" sinbad inquired hoping not to sound too concerned. "if you
must know, dear captain, i plan on slicing your brother"s throat, like this." and with a single
quick movement his blade slid through ji"s skin. he just smiled as the boy"s yell was quieted with
his last breath. sinbad tried to reach ji, but it was too late. the air slipped from the boy"s neck
as he slumped dead on the deck. "no!" sinbad cried, trying to block ruadh as he grabbed for his
captor with only one thought in mind, revenge. but it was not to happen for they were clubbed from
behind and claimed by the blackness that felled them. when sinbad awoke he found himself bound hand
and foot, hanging upside down, tied fast to the side of his ship. he saw that two of the longboats
had launched and the pirate captain stood in front of him from the bow of one. "where are my men?"
sinbad whispered, his head still pounding with the thought of what this man had and could do with no
conscious concern or care. "i have yet to decide which i will let live to tell your brother what i
have done. do you have a preference?" he asked mockingly. "why?" sinbad groaned, for his whole body
hurt and he knew the worst was yet to come. "what do you want with my brother?" the man smiled,
certain the last thoughts of the nomad"s captain should be of his brother"s violent death. "an eye
for an eye, my dear captain. i intend to have doubar return to the same discovery as i had when i
returned to my ship nearly two years ago. "you see, captain, your brother interferred in what should
have been a simple raid on a port village just south of baghdad. seems he did not approve of the
choice of wenches my brother chose to have that night. doubar, alone, killed 11 men, my brother
among them." i have waited a long time to deal out an adequate punishment but you are a difficult
man to catch up with. have you ever seen a man keel- hauled captain?" sinbad looked around. his
blood was pounding its way to his head. he could see no way out of his predicament, and when doubar
returned, just as this man had done, he would seek revenge blindly. sinbad felt them yank taught on
the ropes that bound him. he felt his shoulders dislodged from their socket as he was slowly
submerged below the water. he knew not to struggle if he had any chance of survival he had to
maintain his air. and he had to survive or doubar would play right into this monster"s hands and
die. he would not give him the satisfaction of his death, as long as he was alive doubar would not
leave him. allah help me save my brother. sinbad"s mind quickly filled with the visions of death as
the barnacle and splintered wood ripped and tore at his skin and clothes. it was not long before he
felt his life force try to slip away. the pain had grown too intense and he had not reached the
spine of the ship. fool that he was ... how did he plan to fight such a formidable foe as death, and
expect to win. blood filled the water around him. his faith and hope lost in the tattered remains of
his mind. he finally gave in to the need to struggle against the ropes. his face and chest were
being scraped against the sand and shells on the bottom of the inlet. the cutting and burning became
more than he could bare. blood tinged red the water around him. the world was quickly growing dark.
then the ropes around his ankles snagged on the center rib of the ship and he knew he would surely
drown unless he could free himself. they yanked him free but not before the rope had began to
unravel in his attempt for freedom. it gave him a small ray of hope in was seemed like total
darkness. his lungs screamed in agony as the last of his air soured in them. would death win and his
brother die as well at the hands of this creature. no his mind screamed clinging to the last thread
of faith in his being. "no!" he defied as the last of his air was expelled. all was lost but still
he would not yield. then suddenly his head broke the surface of the water and his mind began to
laugh as his lungs dragged its precious find greedily back into him " allah forgive my boldness but
i will not die" he thought " i will not let him take my brother." and with those words the world
went black. firouz felt sick as his captors had forced him to watch the spectacle. they held them to
the rail and laughed as the inlet went red with blood, sinbad"s blood. and he thought he would die
of horror when the line became snared on something below. allah forgive him but in that moment of
panic he grabbed hold of the rope and though, felt he was aiding them in murder, he yanked with all
he had till the rope began to move again. and he felt it, the moment that his friends body went
still and realized nobody, not even sinbad could ever have survived what they had done. chapter 2
not till sinbad"s limp body was being hauled up the side of the ship did the rope binding his legs
snap, tossing the men on the ropes to the deck giving ruadh an opening for attack. he easily
disarmed the closest man to him, while firouz tried to pull sinbad up, but he did not have the
strength against the dead weight of his friend so he tied off the rope. it was then he spotted the
activity in the water. the blood had attracted some more uninvited guest; sharks were circling the
ship in a frenzy not unlike what was happening on the deck of nomad. the boy had managed to kill
three of the assailant, but he flung a fourth into firouz slamming him hard in to the rail. by the
time the physician was able to gain his footing again the other pirates had come back on board and
after a great struggle their leader had the boy restrained and balanced over his head. when sinbad
came to he was choking. he no longer felt any pain, and even though his vision was blurred he could
see the blood that stained the water had attracted sharks. he hung precariously above them like a
morsel to tease them. desperately he tried to yell, but his words only jarred themselves in his
swollen throat. air was a precious commodity so he remained still, until he heard what sounded like
firouz screaming out and laughter, lots of loud, evil, laughter. then something fell into his view.
it was ruadh. "allah no!" they tossed the boy into shark infested waters. he saw him try desperately
to grab on to the side of the ship he heard the lad"s pleas for help. sinbad tried to break free of
the ropes but found he had no control of movement he could do no more than hang there and watch as
the young man was hit repeatedly by the creatures till he was pulled under for the last time. he had
brought these young men on a voyage of doom and left another alone without family back in basra.
"allah forgive me" he prayed. but maybe even allah could not forgive him for he kept seeing ruadh"s
death over and over, till he wanted to scream and yet even that was impossible. eventually the
vision changed and it was no longer ruadh that was screaming for help, but doubar and still he could
not move, he could not scream. he could only watch and listen to the laughter as his brother too was
dragged below the water"s surface. it kept repeating until all of a sudden he felt no need to
struggle, no need to scream, no need to care. and the blackness returned to a grateful recipient.
when firouz finished retching he was flung to the deck at the foot of his captor. "who are you?" he
cried out. "what do you want from me!" tears filled the scientist eyes, never in his life with all
the death and horrors he had encountered did he ever see such mindless cruelty. "i am allah"s
revenge, i am mahmoud the brother to enver dmirtis. i am the wraith that will haunt doubar to the
ends of this earth. i am death. with that firouz"s head filled with pain and he gladly sunk in to
the coiling threads of darkness. ***** doubar and rongar were returning to the ship. it had been a
long and quite adventurous trip to every pub on the island. oh they were light headed but they were
sure they were ready to weigh anchor at tide "and that was all he asked." doubar thought laughing.
as the crew worked their way closer to the ship they could sense something was wrong. where was
everyone. "why did they take down the nets?" doubar questioned, "ahoy! little brother. we are not
that late. lower the ropes or something?" rongar pulled down on doubar shoulder his hands flying in
a series of signals that told doubar that something was wrong. he started to growl back at the moor
when another crewman noticed the sharks in the water. it was then that they felt panic seize up
inside them. rongar cupped his hand to let one of the smaller crewmen get boosted to the side of the
ship. the man paused, swallowed, then found a rope and lowered it down to the others who quickly
climbed up to see how truly immense their problems were. doubar was the first to board the nomad.
its deck was covered in blood and lying in the middle was sinbad"s sword. he sobered at the
realization that the ship was abandoned, the one thing sinbad would not do willingly. he hit the
hatchway without opening it and the door splintered into a million pieces. "sinbad!" he bellowed.
the sound echoed off the walls but no other sound was made and as he reached the cargo hold his
hopes were dwindling. all he could remember was the blood on the deck. "sinbad!, firouz! someone
answer me!" he bellowed. just as he busted down the cargo door, firouz fell out of the room swinging
his sword haplessly at any thing he could see. rongar was able to lock his arms around the injured
man. it took a couple minutes before the scientist realized he was safe, that it was the rest of the
crew. then the wall of fear crumbled only to be replaced by the all to recent memories of the
horrors he witnessed. tears fell as he slipped to the ground mumbling about pirates, murder,and
sinbad. "they were after you... they killed him.... they killed them all." firouz sobbed, repeating
himself. doubar didn"t want to hear what he thought he had. he grabbed the man by the shoulders and
shook him as hard as he could. "firouz what happen?!" rongar stepped between them breaking the big
mans grip ...he silenced him by holding his hand over his mouth and signaled for them to listen.
just then a sailor ran into the room looking as though he was being chased by a ghost. "we found the
captain..." he screamed out "... they keelhauled him ..firouz! thank the gods they found you" he
swallowed " you will be needed. he"s alive." it took every bit of stamina for firouz to stand but he
followed the young crewman out of the lower decks. as they listen he explained that they found
sinbad hanging off the side of the ship. they had just laid him on deck when firouz and doubar
reached them. sinbad was unconscious and pale. if not for the quick rasping breath, firouz would not
have believed he still lived. "there"s water in his lungs" the physician mumbled as he turned the
captain on his side but just as he went to try and pound the water loose, he froze in his tracks.
doubar looked quizzically at him "firouz ? what"s wrong? will he live?" its been a question he has
asked all to often. "god i hope not." his friend wretched, not realizing "til it was too late that
he had said it out loud. he would never wish harm on anyone, especially sinbad, but as he lay sinbad
on his stomach half the crew made for the rails as they retched and heaved the contents of their
bellies over the side. others did not make it that far. doubar dropped to his knees his face went
white, and his heart emptied as he stared at the ripped shards of skin and bone. even splinters of
wood and gravel were visible in what was left of his brother"s back arms and legs. fear and concern
quickly faded to rage. he would avenge this atrocity. he wanted nothing more than that which he
believed due sinbad. the slow death of the attacker by his hand. firouz took doubar by the arm and
pulled him aside. he knew doubar"s thoughts as well as his own, but his brother would need him here,
at least until the captain gave in to the dark specter he now fought somewhere deep in his tattered
soul. but what if the captain did live. then what? he stared down at the wounds and felt his own
heart break. his next words would probably only fuel the fire of hate that grew within the big man
but he needed to know the truth as much as firouz need to defy it. "you need to understand something
doubar, there is very little i can do. i have never seen anyone live this long, baring wounds as
grave as these. but sinbad has never done things as others. if he survives this, doubar," he
whispered"... it"s not very likely he will have use of his muscular or skeletal systems. paralysis
is a definite possibility, but i won"t know for certain right now." "firouz!" doubar growled, scared
and frustrated by his lack of understanding. firouz just glanced back down at his injured friend and
sighed. "sinbad may never have use of his arms or legs again." suddenly sinbad started to choke.
firouz threw the captain over on his back and pushed down as hard as possible on his stomach. sinbad
started spewing the water from his lungs. doubar turned his brother on his side as the frothy liquid
expelled from him. then his brother fell silent again. doubar thought he had lost him but then
realized sinbad heart was pounding like a jackrabbits and now started to ease. he gasped, then his
breath slowly began to wheeze from his swollen throat. his brother was alive, but for how long and
for what. because of him sinbad would be denied all the things in life he enjoyed and so much more.
rongar watched as the hope in both men withered to the nothingness. firouz bore the blame of a man
who could not heal his friend and doubar the man who took blame for the wounds. both blinded by
their grief rongar grabbed firouz by the shoulders. his hands waving and moving in gestures that
finally got through to his friend. "magic?" firouz quarried "you mean caipra? the moor pointed down
at the captain then patted firouz on the shoulders. "it"s a long shot at best rongar." the physician

In [38]:
# labels_pan20.value_counts()

In [39]:
pan20_stats = pan20.dataset_stats()

In [40]:
# pan20.plot_text_length_histogram(bins=50)

In [41]:
# def normalize_text(text):
#     stemmer = SnowballStemmer('english')
#     return ' '.join(stemmer.stem(w) for w in text.lower().split())

In [42]:
# FIXME: kernel fails

# impostor_det = ImpostorDetector(ds_pan, top_n=250, portion_delete=0.5, shared_vocab_only=True)

# preproc_fn = partial(impostor_det.tokenize_char_ngrams, n=4, normalize_ws=True, space_free=True)
# pan20.plot_text_length_histogram(bins=50, preprocess_fn=preproc_fn)

In [43]:
# pan20.plot_avg_text_length_per_author()

In [44]:
# pan20.plot_avg_text_length_per_author(unit='ngrams')

In [45]:
# pan20.boxplots_text_len_ngrams()

In [46]:
# Python garbage collector to release memory
del pan20
gc.collect()

23

## Blog Corpus

In [47]:
blog = datasets.BlogVisualization()

In [48]:
ds_blog = blog.load_dataset()

The shortest blog text (500 words) is an experience report from a McLachlan concert.

In [49]:
print_min_len_text_sample(ds_blog)

Text with minimal length 500:
last night was the sarah mclachlan concert. it was so wonerful. butterfly boucher opened and was
really good. the lines were too long to purcahase her cd so i will investigate on-line. sarah sang 9
songs from afterglow and 10 from mirrorball. there were about 3 or 4 that i did not know. and she
sang black bird - i love that song. this concert is not like a madonna or any of the boy bands.
there were no dancers or gimicks. she walked out on stage in jeans and a spaghetti strap tank top
type shirt. perfect! she looks great. we had great seats. and when we felt we needed more detail
there were two large screens on either side of her. she was even wearing one of the yellow lance
armstrong bracelets. one thing that i loved was when she was on stage alone with a spot light and
sang 'you are my sunshine' as the intro to 'hold on', which was perfect. she talked to the audience
with such ease - she is good at what she does. everything was so perfect. her band left the stage
and i told my sweetie to wait for an encore. he mumbled something about artists not doing encores
anymore. haha i was right. she came back out to sing like 5 or 6 songs. she just kept coming back on
:-) the last time she came out all the equipment was in the process of being packed up so she took
to the piano and finished from a song from afterglow. it was like i knew her. it is funny there is a
friend of mine that is very confident and powerful. sarah sounded just like her. we both were
reminded of the dark diva. i will have to tell her and hope it is not an insult :-) i believe music
is very important. it stimulate learning and encourages thinking in a way that a text book cannot.
while i do not currently play an instrument - i do listen to music. however, i do not listen to
music in the way of mindless on the radio. i am sure i am not the only one. whenever i have a rough
time in my life i turn to music - normally one artist - and completely embreace the albulm. it helps
me deal with the issues. this has been true since i was in junior high and chicago helped me through
a breakup. i love sarah mclachlan. however, i have not always been a die hard fan - heck i did not
know about 4 songs last night. but her cd mirrorball helped me through one of the roughest patches
in my life. for that i will always be grateful to her and her music. i listened to this cd almost
daily for a year. it was my therapy. and it was amazing to experience my therapy live. this has to
be the best valentines present from my sweetie.

The longest Blog entry (8663 words) seems to be a fictional book/ story.

In [50]:
print_max_len_text_sample(ds_blog)

Text with maximal length 8663:
sink to the bottom with you by catalina chapter seventeen: all roads lead to midgar i just cant
believe this shit! cid highwind cid highwinds deep blue eyes were as thunderous and stormy as the
ocean as he stood underneath the wing of the tiny bronco, covered from head to toe in a black rain
slicker, complete with dark boots over his already booted feet. a cigarette dangled from his thin
lips, the lighted tip of it the only thing that lent illumination to the shadow cast by his plastic
hood. the light danced over his cheekbones, set high in his almost haggard face, creating hollows of
inky shadows beneath the strong bones. it also lent an orangish-yellow illumination to his deep blue
eyes, making them look like they were smoldering with fire in the literal sense as well as the
figurative. bastard, he suddenly mumbled, cigarette dancing on his thin lips as he spoke. a bit of
ash floated down to sand beneath his feet. barret turned to glare at him. you talkin to me, foo? cid
blinked at his companion. naw. barret snorted and turned away again, the movement of his head
unsettling the stubborn raindrops still clinging to the hood of his slicker. you talkin to yerself,
then? no, cid growled, blowing smoke out of his nostrils in annoyance. i just cant believe this
shit! i hear ya, barret echoed grumpily, shifting his weight from foot to foot. the man was so tall
he had to crouch slightly to fit under the wing of the tiny bronco. i mean, cid continued to rant.
we busted our asses yesterday, climbing the mountains, riding the waves, to get to that cave to look
for that damn ship, and the @#$&ing thing ends up on the beach! and sure enough, fifty feet away
from where cid and barret were standing miserably underneath the wing of the tiny bronco, the ghost
ship that had very un-ghostlike qualities was sitting on the beach with a certain smugness that
seemed directed at the two men. everything about the ship from its broken mast to the rotted boards
of its hull appeared to gloat at cid and barret, teasing them about the hard work they had endured
the day before, belittling their actions and making fun of their anger. look at me, it seemed to
say. im made of rotting, termite-filled wood held together by rusty nails, and i outsmarted you!
hahahahahaha! cid spat at the sand. goddamn hunk of crap, he cursed. well, getting your panties in a
twist about it aint gonna make all our hard work worthwhile, ya know, barret grumbled, striving to
be the sensible one now that cid was all huffy and puffy over a stupid ship. cid crossed his arms
over his chest and cursed softly when his cigarette was almost extinguished by the water sitting on
his sleeve. shut up, he told his companion. i had a feeling something like this was gonna happen.
then why the hell did ya drag me out here this morning? barret growled, adjusted his way-too-small
slicker with his normal arm. im cold, im wet, and this damn slicker thang smells like booty!
probably cause i gave you the one that was kept outside by the septic tank, cid said, calmly puffing
on his cigarette. barret turned an amusing shade of green and whirled on his companion, glaring down
at the smaller man. foo, youd best be joking or im gonna bust a cap in your ass! i did attach my
gun-arm this mornin ya know! cid grinned. i can see that. i aint blind. i was just joking, anyways.
best be, barret grumbled, folding his arms across his chest, a little peeved that his companion had
managed to make him loose his cool with one off-the-wall comment. he had promised marlene that he
was going to work on keeping his temper in check, and goddamn it, he was gonna try his hardest! then
cid went and ruined it. i gave you the one i found in my chocobos pen. barret blew his cool again.
what?! the hell you put a coat in the chocobos pen anyways, foo?! cid scowled and blew smoke out of
his nostrils. he didnt have no hay! didnt want the poor bird-brain to have nothing to lay on! are
you gonna shoot me for being nice to my chocobo? you aint nice to your bird, cid! you didnt even
feed him yesterday! did too! i fed him in the morning! yeah, well, i fed him again in the evening,
seeing that you didnt do it! you aint supposed to feed chocobos that much food! now hes gonna get
fat! barrets scowl deepened. you supposed to feed chocobos two times a day! two, foo! he held up two
fingers of his normal hand. cids mouth fell open, but he managed to keep an expert grip on his
cigarette. you shittin me? he demanded of his tall companion. i didnt know that. barret threw his
arms up in exasperation. no wonder the damn bird is always eating my birdies food! birdie? cid
repeated, then burst out laughing. barret flushed and made another mean face at his amused friend.
shuup, foo! thats what my little girl calls em! cid continued laughing, clutching his sides in
mirth. barret folded his arms across his chest again, offended. i give up on you, cid! ya need
serious help or somethin! now what was we talkin bout before? where i got your coat from, cid
managed to say through his snickering. before that, foo! cid gave it some thought after he finished
his laughing fit. hmmm. oh yeah! we was talking about how @#%$ing stupid it was for us to be out
here in the rain, all wet and cold, just staring at a stupid ship on the beach! he pointed to the
ghost ship sitting on the shore to prove his point. the rotting thing stared back as if to say, who
me? if its so stupid, barret grumbled. then why did ya drag me out here? yeah! thats what i was
askin! cid shrugged. you were the only one awake and dumb enough to come with me. barret gritted his
teeth and counted to ten (just like marlene told him to do) before he trusted himself to answer cid.
lets go back to the bar, foo. im done standing out here admiring this old hunk of crap. the brat
yuffie was right; it sure is one ugly son of a jackal. cid snickered at barrets euphemism, but made
no move to restart the tiny bronco. instead he said, you think cloud will have his head screwed on
straight and right side up when we get back? hed better, barret growled, eyes still on the falling
rain. or someone else is gonna have to take command. he glanced at cid. be ready, foo. we probably
nominate you. cid chewed on that for a while, then shook his head. naw. you know there aint nothing
that can keep spike down for long. i think hes gonna be just fine by the time we get back. i believe
in the kid! barret scowled down at his friend, offended. so do i! dont talk like i aint got no faith
in the spikey-headed idiot! sides, probably aint his fault, what happened yesterday. its that
goddamn reno! cid snorted in distaste, smoke exiting his nose in two funnels as he did so. that
@#$%ing turk, he snarled. trouble follows him wherever he goes. i cant believe we has to work wit
em, barret mumbled. its only for a little while, cid said. hes good in a battle, and them turks are
friends of that damn cat so i guess they cant be that bad once you really, really, really, think
about it. thats a lot of reallys, man. i dont think i can think that hard. cid ignored him. now,
rude and even that loud-mouthed elena aint bad at all. rude dont say much, and elena usually dont
put up too much of a fight about our decisions because she so insecure about herself. its just that
reno that i think is gonna give us problems. he looked up at barret from under the shadow of his
hood. what you think? barret shook his head with sudden weariness. i aint in no mood to be thinkin
right now. i just want to find reeve and get this whole damn thing over with. i have a daughter to
raise and take care of. shes gonna be going to school soon, ya know. cid nodded silently. he knew
that barret probably loved his little girl more than anything on the face of the planet. probably
more than the planet itself. but barrets love for his daughter was something cid could understand.
he loved his wife, shera in such a fashion. all that stuff about fighting for the planet was all
just a load of crap, to put it in a not-so-nice way. cid was fighting for shera. everything he did,
he did with his wifes well being in mind. sometimes, he was surprised at how much he had changed in
only one year, and he had shera and avalanche to thank for it. it may have taken him years and years
to realize just where his heart belonged, but now that he did know, he couldnt have been happier. i
can understand, you know, cid suddenly told barret. about marlene and all. barret glanced at him
thoughtfully. i know ya can. you probably the only one that can, once ya really think about it. cid
grinned up at his large companion again. i thought you said you wasnt in the mood for thinkin? with
a frustrated cry, barret threw his hands up in the air again. he could tell it was going to be one
hell of a long day. * * * * * * * * * tifa sighed as she pulled the shoelaces tight on her fighters
boots, double knotting them like she always did so they wouldnt come loose in the middle of battle.
she hadnt gotten much sleep last night, and she knew that her lack of rest was seriously going to be
weighing her down today if they got into any skirmishes. she hadnt been in a serious, life-
threatening battle in months, and the f she had tossed and turned all night worrying about cloud,
reno, and reeve wasnt going to help her situation at all. too much to worry about and so many things
to do. might as well just give up on having a normal life, she thought glumly, pulling on her
premium heart fighter gloves. there was suddenly a knock at her door, and tifas heart jumped
slightly when she considered that it might be cloud. he hadnt spoken to her all day yesterday, not
that she had given him much of a chance, though. from the barn, she had gone straight upstairs and
barricaded herself in her room, and she had spent the whole afternoon trying to watch tv and ignore
the f cloud was locked up in his room only two doors down. she had thought she had heard him talking
to someone in the bar late last night, but the thunder had been too loud and she had given up on
listening. probably just a figment of her imagination, birthed from her wishful thinking and longing
for cloud. tifa? a voice suddenly called through the door, and the young brunette realized that she
had spaced out. yuffie? tifa asked, recognizing the voice. yup, its me. can i come in? tifa tried
her best not to sound gloomy. sure! come in. the door opened, and a very sleepy-looking yuffie
kisaragi trudged into the room with her feet dragging and her eyes drooping. the young girl offered
her older friend a half-hearted wave with the ghost of her normal spunkiness. then she practically
collapsed on tifas bed, rumpling the sheets and almost sending tifa bouncing to the floor. are you
okay, yuffie? tifa asked with concern flickering in her burgundy eyes. you look absolutely
exhausted. i am, yuffie mumbled, opening one eye to glance at her friend. there were red veins
around the stormy gray iris. i didnt get any sleep last night. bad dreams? tifa asked
sympathetically, smoothing back some of her young friends chocolate brown hair. yuffie nodded
miserably, closing her eyes again. horrible nightmares. the only sleep i got was when i dozed off
taking a shower this morning. it totally sucked. i almost drowned! tifa laughed softly. poor yuffie.
are my clothes still working out for you? yuffie nodded, absently adjusting one of the straps of her
sleeveless tank top. yeah, but i was sort of hoping that my boobs would miraculously grow to fill
out the shirt overnight, but no such luck. darn. tifa laughed again. and the shorts? those are
practically the only pair i had that were small enough to fit you. yuffie nodded sleepily. they keep
slipping, but thats okay. i like them loose. she yawned widely. so tired... you dont have to come
with us today if you dont want to, tifa suggested, getting off the bed and adjusting her suspenders
absent-mindedly. no! yuffie exclaimed suddenly, rising up to a sitting position. im definitely going
with you guys! ive been out of action for too long, and im not going to miss out on any more of it!
tifa raised her hands in mock surrender, a bit surprised at her friends vehemence. hey, hey, calm
down, yuffie. it was just a suggestion. besides, you and vincent have been experiencing most of the
action lately, fighting with those faceless men or whatever they were called. all we were doing was
sitting around worrying about you two. vincent, yuffie muttered under her breath, eyes spacing out
for a second before coming back into focus. is vincent awake yet? she suddenly asked. tifa blinked.
i think so. you never know with that man. i heard cid and barret tripping over stuff earlier this
morning so i know theyre up. as for all the others, i have no earthly idea. yuffie made a half-
hearted effort to stifle a yawn. what are we going to do today? did cloud say anything important
that i might have missed? tifa winced inwardly at the mention of clouds name. no, he didnt say
anything else, but i figure were going to do something today now that were all together again. lets
just go downstairs and see whos up. yuffie nodded dully, her eyes half-shut. that didnt stop tifa
from seeing the spark of humor that suddenly twinkled in their iron gray depths. she lifted her
hands towards tifa. you might have to carry me down the stairs, tifa. id fall and crack my head open
otherwise and cloud would have to mop it up. tifa laughed and tugged yuffie to her feet. that makes
two of us, you know. this is going to be like the blind leading the blind. * * * * * * * cloud
drummed his fingers absent-mindedly on the table and stared at his two friends that were sitting
across from him. you guys have got to be kidding me? he muttered under his breath. barret heard him,
however, and snorted at the young mans lack of confidence. you want to go out there in the rain in
that damn broke plane and take a look for yerself, spike? we tellin you the truth, boy! that ship
jes be sittin there on the beach, all old and rotten like! cloud sighed and rubbed his face with his
hands, letting the rough texture of his gloves grind against his skin. he relished that dull pain. i
know, barret. i wasnt calling you guys liars. i just didnt think wed ever see that damn thing again,
thats all. cid blew a cloud of smoke towards the ceiling. you and me both, kid. cloud allowed a
silence to descend on the almost deserted bar as he fought to gather his thoughts. after he had left
vincent alone in the darkness the night before, he had returned to his room and had actually managed
to get a couple of hours of sleep before waking up at the buttcrack of dawn that morning. cloud had
no idea whether the alcohol lingering in his system or talking with vincent had eased his mind
enough to sleep, but whatever had done it, he was eternally grateful for. for some reason, talking
with the dark gunslinger had always served as a sort of balm to his nerves. it wasnt that vincents
presence was comforting or anything like that. no, nothing so simple. it was kind of sad actually.
whenever cloud looked at or spoke with vincent, he was always thinking in the back of his mind, wow,
all my stupid-ass problems are nothing compared to the hell this guy has gone through. i got off
lucky with just fractured memories and glowing mako eyes. look at his guy! damn, to think i could
have ended up like this! whew! sad, and mean as hell, but it was heartbreakingly true. cloud was
happy he hadnt ended up like vincent, so cold and callous, leaving even his friends to wonder if
there was a heart behind those ruby-red eyes of his. but he hated thinking like that, especially
when vincent was around. he was always afraid that those piercing garnet eyes would suddenly turn
their soul-searching beams on him and dissect his every thought, exposing the darkest corners of his
mind to a man that was practically darkness given shape and form. hell, maybe cloud felt better
after talking with vincent because deep down he thought that vincent was the only one that could
understand him. in any case, cloud had actually gotten some sleep last night before he had roused
himself from his bed to once again sheathe himself in the guise of a leader - a mixed up kid ready
to lead his friends and enemies alike onto the battlefield. thats all he really was, after all. cid
and barret, however, had beaten him in the race to be the earliest riser. cloud had heard the two
older men down in the front room while he was getting ready. from the sound of it, they had been
tripping and stumbling over chairs in the darkness, and cursing loud enough to wake the dead. cid
and barret were definitely not the most graceful or soft-voiced men in the world, and that was for
damn sure. after trying to catch them before they left and failing, cloud had spent about ten
minutes standing in front of tifas door, wondering if he should knock and try and smooth things over
there and then. in the end, however, his weak, prideful heart had failed him, and he had gone
downstairs to stare at the rain and wonder why cid and barret would be taking the tiny bronco out so
early in the morning. but the news they had brought back with them was definitely worth the trip, in
clouds opinion. so the ghost ship is beached on the shore near midgar, he thought, brow creasing as
he sought to derive something useful from the piece of information. according to vincent and yuffies
story, the thing was out on some deep-sea complex the night before last. and we know it wasnt there
yesterday morning because we would have seen it when we went to investigate the cave. i know the
seas are all turbulent right now, but could it have really drifted all this way in less than a day?
my instincts tell me no, unless of course...thats it! barret raised an eyebrow when he saw the look
on clouds face become dangerously contemplative. whatcha thinkin bout, spike? a short, mirthless
laugh emerged from clouds throat. something bad. but let me ask you guys something: do you think the
ship just kind of floated over to the beach, or did someone pilot it there? cids eyes widened when
he realized just what cloud was getting at. the running man! he might have been on the ship - thats
what you sayin right, kid? cloud nodded, some unruly strands of blond hair flopping into his face.
yeah, and did you notice how close that shore is to midgar? barret caught on immediately. you think
the running man is in midgar right now, then? clouds mood was becoming grimmer by the minute. yeah,
and that is exactly where i was planning on heading today. why do you look so sad? cid demanded. if
hes there in midgar, well be able to find that bastard and finally get information out of him! this
is a good thing, im telling ya! i suppose so, cloud muttered, still unnerved by the idea that the
running man had somehow predicted their next course of action. that could only mean one thing: there
was a spy. but he didnt know who it could be, so he didnt want to be making any premature
accusations. of course, the running man could have been heading to midgar just by coincidence. maybe
he had left some unfinished business behind. but either way, cloud wasnt at all comfortable with the
f the man who had kidnapped his friend was going to be running around the same place as they were.
and they were going to all split up, making it easier to target one group at a time. he had to
protect tifa... just then the center figure in his thoughts - in his life - came walking down the
stairs dragging an exhausted-looking yuffie by the arm. good morning, everyone, tifa said cheerfully
as she guided yuffie over to the table and dumped her in the seat next to cloud. the young ninja
immediately swayed to the side, her head landing heavily on clouds shoulder, chocolate brown strands
tickling his bare skin. though he wasnt too happy about all the extra weight, cloud hadnt the heart

In [51]:
blog_stats = blog.dataset_stats()

In [52]:
blog_df = pd.read_csv(
    Path(os.getcwd()).resolve().parent / "data/datasets/Blog_corpus/blogtext.csv"
)
blog_df["date"] = pd.to_datetime(
    blog_df["date"], format="mixed", dayfirst=True, errors="coerce"
)
print(blog_df["date"].agg(["min", "max"]))
print(
    "there is actually entries with date= 01,January,1999 and 23,August,2006, i checked it"
)

min   1999-01-01
max   2006-08-23
Name: date, dtype: datetime64[ns]
there is actually entries with date= 01,January,1999 and 23,August,2006, i checked it

In [53]:
from itertools import chain


# num_words = [len(text.split()) for text in chain.from_iterable(blog_df['pair'])]
print(blog_df.columns)
one_word_rows = blog_df[blog_df["text"].apply(lambda x: len(x.split()) == 1)]
print(f"Number of rows with one word in 'text': {len(one_word_rows)}")
print("Rows with one word in 'text':")
print(one_word_rows[["text", "date", "id"]].head(10))
print(
    "Stats are calculated on the arrow dataset, where entries must have at least 500 words, so these entries are not included in the stats."
)

Index(['id', 'gender', 'age', 'topic', 'sign', 'date', 'text'], dtype='object')
Number of rows with one word in 'text': 4276
Rows with one word in 'text':
                                                   text       date       id
1163                                             URGH   2004-08-12  1932521
1441                                     baak?          2004-08-05   589736
1543                                     niort          2004-08-05   589736
1595                                    quack.          2004-08-05   589736
1619                              TGIF!!!!!!!           2004-08-05   589736
1621                                     FLORA          2004-08-05   589736
1680                                  hmmm....          2004-08-05   589736
1719                                  marzipan          2004-08-05   589736
1737             NIORT!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ... 2004-08-05   589736
1760                                       aye          2004-08-05   589736
Stats are calculated on the arrow dataset, where entries must have at least 500 words, so these entries are not included in the stats.

In [54]:
# blog.plot_avg_text_length_per_author()    # too many authors
# blog.plot_text_length_histogram(bins=50)  # FIXME: dataset comes already preprocessed
# blog.boxplots_text_len_ngrams()

In [55]:
# Python garbage collector to release memory
del blog
gc.collect()

0

## Gutenberg

In [56]:
gutenberg = datasets.GutenbergVisualization()

In [57]:
ds_gutenberg = gutenberg.load_dataset()

In [58]:
print_min_len_text_sample(ds_gutenberg)

Text with minimal length 11443:
when mr. hiram b. otis, the american minister, bought canterville chase, every one told him he was
doing a very foolish thing, as there was no doubt at all that the place was haunted. indeed, lord
canterville himself, who was a man of the most punctilious honour, had felt it his duty to mention
the f mr. otis when they came to discuss terms. "we have not cared to live in the place ourselves,"
said lord canterville, "since my grandaunt, the dowager duchess of bolton, was frightened into a
fit, from which she never really recovered, by two skeleton hands being placed on her shoulders as
she was dressing for dinner, and i feel bound to tell you, mr. otis, that the ghost has been seen by
several living members of my family, as well as by the rector of the parish, the rev. augustus
dampier, who is a fellow of king's college, cambridge. after the unfortunate accident to the
duchess, none of our younger servants would stay with us, and lady canterville often got very little
sleep at night, in consequence of the mysterious noises that came from the corridor and the
library." "my lord," answered the minister, "i will take the furniture and the ghost at a valuation.
i have come from a modern country, where we have everything that money can buy; and with all our
spry young fellows painting the old world red, and carrying off your best actors and prima-donnas, i
reckon that if there were such a thing as a ghost in europe, we'd have it at home in a very short
time in one of our public museums, or on the road as a show." "i fear that the ghost exists," said
lord canterville, smiling, "though it may have resisted the overtures of your enterprising
impresarios. it has been well known for three centuries, since 1584 in fact, and always makes its
appearance before the death of any member of our family." "well, so does the family doctor for that
matter, lord canterville. but there is no such thing, sir, as a ghost, and i guess the laws of
nature are not going to be suspended for the british aristocracy." "you are certainly very natural
in america," answered lord canterville, who did not quite understand mr. otis's last observation,
"and if you don't mind a ghost in the house, it is all right. only you must remember i warned you."
illustration: miss virginia e. otis a few weeks after this, the purchase was concluded, and at the
close of the season the minister and his family went down to canterville chase. mrs. otis, who, as
miss lucretia r. tappan, of west 53d street, had been a celebrated new york belle, was now a very
handsome, middle-aged woman, with fine eyes, and a superb profile. many american ladies on leaving
their native land adopt an appearance of chronic ill-health, under the impression that it is a form
of european refinement, but mrs. otis had never fallen into this error. she had a magnificent
constitution, and a really wonderful amount of animal spirits. indeed, in many respects, she was
quite english, and was an excellent example of the f we have really everything in common with
america nowadays, except, of course, language. her eldest son, christened washington by his parents
in a moment of patriotism, which he never ceased to regret, was a fair-haired, rather good-looking
young man, who had qualified himself for american diplomacy by leading the german at the newport
casino for three successive seasons, and even in london was well known as an excellent dancer.
gardenias and the peerage were his only weaknesses. otherwise he was extremely sensible. miss
virginia e. otis was a little girl of fifteen, lithe and lovely as a fawn, and with a fine freedom
in her large blue eyes. she was a wonderful amazon, and had once raced old lord bilton on her pony
twice round the park, winning by a length and a half, just in front of the achilles statue, to the
huge delight of the young duke of cheshire, who proposed for her on the spot, and was sent back to
eton that very night by his guardians, in floods of tears. after virginia came the twins, who were
usually called "the star and stripes," as they were always getting swished. they were delightful
boys, and, with the exception of the worthy minister, the only true republicans of the family.
illustration: "had once raced old lord bilton on her pony" as canterville chase is seven miles from
ascot, the nearest railway station, mr. otis had telegraphed for a waggonette to meet them, and they
started on their drive in high spirits. it was a lovely july evening, and the air was delicate with
the scent of the pinewoods. now and then they heard a wood-pigeon brooding over its own sweet voice,
or saw, deep in the rustling fern, the burnished breast of the pheasant. little squirrels peered at
them from the beech-trees as they went by, and the rabbits scudded away through the brushwood and
over the mossy knolls, with their white tails in the air. as they entered the avenue of canterville
chase, however, the sky became suddenly overcast with clouds, a curious stillness seemed to hold the
atmosphere, a great flight of rooks passed silently over their heads, and, before they reached the
house, some big drops of rain had fallen. standing on the steps to receive them was an old woman,
neatly dressed in black silk, with a white cap and apron. this was mrs. umney, the housekeeper, whom
mrs. otis, at lady canterville's earnest request, had consented to keep in her former position. she
made them each a low curtsey as they alighted, and said in a quaint, old-fashioned manner, "i bid
you welcome to canterville chase." following her, they passed through the fine tudor hall into the
library, a long, low room, panelled in black oak, at the end of which was a large stained glass
window. here they found tea laid out for them, and, after taking off their wraps, they sat down and
began to look round, while mrs. umney waited on them. suddenly mrs. otis caught sight of a dull red
stain on the floor just by the fireplace, and, quite unconscious of what it really signified, said
to mrs. umney, "i am afraid something has been spilt there." "yes, madam," replied the old
housekeeper in a low voice, "blood has been spilt on that spot." illustration: "blood has been
spilled on that spot" "how horrid!" cried mrs. otis; "i don't at all care for blood-stains in a
sitting-room. it must be removed at once." the old woman smiled, and answered in the same low,
mysterious voice, "it is the blood of lady eleanore de canterville, who was murdered on that very
spot by her own husband, sir simon de canterville, in 1575. sir simon survived her nine years, and
disappeared suddenly under very mysterious circumstances. his body has never been discovered, but
his guilty spirit still haunts the chase. the blood-stain has been much admired by tourists and
others, and cannot be removed." "that is all nonsense," cried washington otis; "pinkerton's champion
stain remover and paragon detergent will clean it up in no time," and before the terrified
housekeeper could interfere, he had fallen upon his knees, and was rapidly scouring the floor with a
small stick of what looked like a black cosmetic. in a few moments no trace of the blood-stain could
be seen. "i knew pinkerton would do it," he exclaimed, triumphantly, as he looked round at his
admiring family; but no sooner had he said these words than a terrible flash of lightning lit up the
sombre room, a fearful peal of thunder made them all start to their feet, and mrs. umney fainted.
"what a monstrous climate!" said the american minister, calmly, as he lit a long cheroot. "i guess
the old country is so overpopulated that they have not enough decent weather for everybody. i have
always been of opinion that emigration is the only thing for england." "my dear hiram," cried mrs.
otis, "what can we do with a woman who faints?" "charge it to her like breakages," answered the
minister; "she won't faint after that;" and in a few moments mrs. umney certainly came to. there was
no doubt, however, that she was extremely upset, and she sternly warned mr. otis to beware of some
trouble coming to the house. "i have seen things with my own eyes, sir," she said, "that would make
any christian's hair stand on end, and many and many a night i have not closed my eyes in sleep for
the awful things that are done here." mr. otis, however, and his wife warmly assured the honest soul
that they were not afraid of ghosts, and, after invoking the blessings of providence on her new
master and mistress, and making arrangements for an increase of salary, the old housekeeper tottered
off to her own room. the storm raged fiercely all that night, but nothing of particular note
occurred. the next morning, however, when they came down to breakfast, they found the terrible stain
of blood once again on the floor. "i don't think it can be the fault of the paragon detergent," said
washington, "for i have tried it with everything. it must be the ghost." he accordingly rubbed out
the stain a second time, but the second morning it appeared again. the third morning also it was
there, though the library had been locked up at night by mr. otis himself, and the key carried up-
stairs. the whole family were now quite interested; mr. otis began to suspect that he had been too
dogmatic in his denial of the existence of ghosts, mrs. otis expressed her intention of joining the
psychical society, and washington prepared a long letter to messrs. myers and podmore on the subject
of the permanence of sanguineous stains when connected with crime. that night all doubts about the
objective existence of phantasmata were removed for ever. the day had been warm and sunny; and, in
the cool of the evening, the whole family went out to drive. they did not return home till nine
o'clock, when they had a light supper. the conversation in no way turned upon ghosts, so there were
not even those primary conditions of receptive expectations which so often precede the presentation
of psychical phenomena. the subjects discussed, as i have since learned from mr. otis, were merely
such as form the ordinary conversation of cultured americans of the better class, such as the
immense superiority of miss fanny devonport over sarah bernhardt as an actress; the difficulty of
obtaining green corn, buckwheat cakes, and hominy, even in the best english houses; the importance
of boston in the development of the world-soul; the advantages of the baggage-check system in
railway travelling; and the sweetness of the new york accent as compared to the london drawl. no
mention at all was made of the supernatural, nor was sir simon de canterville alluded to in any way.
at eleven o'clock the family retired, and by half-past all the lights were out. some time after, mr.
otis was awakened by a curious noise in the corridor, outside his room. it sounded like the clank of
metal, and seemed to be coming nearer every moment. he got up at once, struck a match, and looked at
the time. it was exactly one o'clock. he was quite calm, and felt his pulse, which was not at all
feverish. the strange noise still continued, and with it he heard distinctly the sound of footsteps.
he put on his slippers, took a small oblong phial out of his dressing-case, and opened the door.
right in front of him he saw, in the wan moonlight, an old man of terrible aspect. his eyes were as
red burning coals; long grey hair fell over his shoulders in matted coils; his garments, which were
of antique cut, were soiled and ragged, and from his wrists and ankles hung heavy manacles and rusty
gyves. "my dear sir," said mr. otis, "i really must insist on your oiling those chains, and have
brought you for that purpose a small bottle of the tammany rising sun lubricator. it is said to be
completely efficacious upon one application, and there are several testimonials to that effect on
the wrapper from some of our most eminent native divines. i shall leave it here for you by the
bedroom candles, and will be happy to supply you with more, should you require it." with these words
the united states minister laid the bottle down on a marble table, and, closing his door, retired to
rest. illustration: "i really must insist on your oiling those chains" for a moment the canterville
ghost stood quite motionless in natural indignation; then, dashing the bottle violently upon the
polished floor, he fled down the corridor, uttering hollow groans, and emitting a ghastly green
light. just, however, as he reached the top of the great oak staircase, a door was flung open, two
little white-robed figures appeared, and a large pillow whizzed past his head! there was evidently
no time to be lost, so, hastily adopting the fourth dimension of space as a means of escape, he
vanished through the wainscoting, and the house became quite quiet. on reaching a small secret
chamber in the left wing, he leaned up against a moonbeam to recover his breath, and began to try
and realize his position. never, in a brilliant and uninterrupted career of three hundred years, had
he been so grossly insulted. he thought of the dowager duchess, whom he had frightened into a fit as
she stood before the glass in her lace and diamonds; of the four housemaids, who had gone into
hysterics when he merely grinned at them through the curtains on one of the spare bedrooms; of the
rector of the parish, whose candle he had blown out as he was coming late one night from the
library, and who had been under the care of sir william gull ever since, a perfect martyr to nervous
disorders; and of old madame de tremouillac, who, having wakened up one morning early and seen a
skeleton seated in an armchair by the fire reading her diary, had been confined to her bed for six
weeks with an attack of brain fever, and, on her recovery, had become reconciled to the church, and
broken off her connection with that notorious sceptic, monsieur de voltaire. he remembered the
terrible night when the wicked lord canterville was found choking in his dressing-room, with the
knave of diamonds half-way down his throat, and confessed, just before he died, that he had cheated
charles james fox out of 50,000 at crockford's by means of that very card, and swore that the ghost
had made him swallow it. all his great achievements came back to him again, from the butler who had
shot himself in the pantry because he had seen a green hand tapping at the window-pane, to the
beautiful lady stutfield, who was always obliged to wear a black velvet band round her throat to
hide the mark of five fingers burnt upon her white skin, and who drowned herself at last in the
carp-pond at the end of the king's walk. with the enthusiastic egotism of the true artist, he went
over his most celebrated performances, and smiled bitterly to himself as he recalled to mind his
last appearance as "red reuben, or the strangled babe," his debut as "guant gibeon, the blood-sucker
of bexley moor," and the furore he had excited one lovely june evening by merely playing ninepins
with his own bones upon the lawn-tennis ground. and after all this some wretched modern americans
were to come and offer him the rising sun lubricator, and throw pillows at his head! it was quite
unbearable. besides, no ghost in history had ever been treated in this manner. accordingly, he
determined to have vengeance, and remained till daylight in an attitude of deep thought. the next
morning, when the otis family met at breakfast, they discussed the ghost at some length. the united
states minister was naturally a little annoyed to find that his present had not been accepted. "i
have no wish," he said, "to do the ghost any personal injury, and i must say that, considering the
length of time he has been in the house, i don't think it is at all polite to throw pillows at him,"
--a very just remark, at which, i am sorry to say, the twins burst into shouts of laughter. "upon
the other hand," he continued, "if he really declines to use the rising sun lubricator, we shall
have to take his chains from him. it would be quite impossible to sleep, with such a noise going on
outside the bedrooms." for the rest of the week, however, they were undisturbed, the only thing that
excited any attention being the continual renewal of the blood-stain on the library floor. this
certainly was very strange, as the door was always locked at night by mr. otis, and the windows kept
closely barred. the chameleon-like colour, also, of the stain excited a good deal of comment. some
mornings it was a dull (almost indian) red, then it would be vermilion, then a rich purple, and once
when they came down for family prayers, according to the simple rites of the free american reformed
episcopalian church, they found it a bright emerald-green. these kaleidoscopic changes naturally
amused the party very much, and bets on the subject were freely made every evening. the only person
who did not enter into the joke was little virginia, who, for some unexplained reason, was always a
good deal distressed at the sight of the blood-stain, and very nearly cried the morning it was
emerald-green. the second appearance of the ghost was on sunday night. shortly after they had gone
to bed they were suddenly alarmed by a fearful crash in the hall. rushing down-stairs, they found
that a large suit of old armour had become detached from its stand, and had fallen on the stone
floor, while seated in a high-backed chair was the canterville ghost, rubbing his knees with an
expression of acute agony on his face. the twins, having brought their pea-shooters with them, at
once discharged two pellets on him, with that accuracy of aim which can only be attained by long and
careful practice on a writing-master, while the united states minister covered him with his
revolver, and called upon him, in accordance with californian etiquette, to hold up his hands! the
ghost started up with a wild shriek of rage, and swept through them like a mist, extinguishing
washington otis's candle as he passed, and so leaving them all in total darkness. on reaching the
top of the staircase he recovered himself, and determined to give his celebrated peal of demoniac
laughter. this he had on more than one occasion found extremely useful. it was said to have turned
lord raker's wig grey in a single night, and had certainly made three of lady canterville's french
governesses give warning before their month was up. he accordingly laughed his most horrible laugh,
till the old vaulted roof rang and rang again, but hardly had the fearful echo died away when a door
opened, and mrs. otis came out in a light blue dressing-gown. "i am afraid you are far from well,"
she said, "and have brought you a bottle of doctor dobell's tincture. if it is indigestion, you will
find it a most excellent remedy." the ghost glared at her in fury, and began at once to make
preparations for turning himself into a large black dog, an accomplishment for which he was justly
renowned, and to which the family doctor always attributed the permanent idiocy of lord
canterville's uncle, the hon. thomas horton. the sound of approaching footsteps, however, made him
hesitate in his fell purpose, so he contented himself with becoming faintly phosphorescent, and
vanished with a deep churchyard groan, just as the twins had come up to him. illustration: "the
twins ... at once discharged two pellets on him" on reaching his room he entirely broke down, and
became a prey to the most violent agitation. the vulgarity of the twins, and the gross materialism
of mrs. otis, were naturally extremely annoying, but what really distressed him most was that he had
been unable to wear the suit of mail. he had hoped that even modern americans would be thrilled by
the sight of a spectre in armour, if for no more sensible reason, at least out of respect for their
natural poet longfellow, over whose graceful and attractive poetry he himself had whiled away many a
weary hour when the cantervilles were up in town. besides it was his own suit. he had worn it with

In [59]:
print_max_len_text_sample(ds_gutenberg)

Text with maximal length 157277:
emma woodhouse, handsome, clever, and rich, with a comfortable home and happy disposition, seemed to
unite some of the best blessings of existence; and had lived nearly twenty-one years in the world
with very little to distress or vex her. she was the youngest of the two daughters of a most
affectionate, indulgent father; and had, in consequence of her sisters marriage, been mistress of
his house from a very early period. her mother had died too long ago for her to have more than an
indistinct remembrance of her caresses; and her place had been supplied by an excellent woman as
governess, who had fallen little short of a mother in affection. sixteen years had miss taylor been
in mr. woodhouses family, less as a governess than a friend, very fond of both daughters, but
particularly of emma. between them it was more the intimacy of sisters. even before miss taylor had
ceased to hold the nominal office of governess, the mildness of her temper had hardly allowed her to
impose any restraint; and the shadow of authority being now long passed away, they had been living
together as friend and friend very mutually attached, and emma doing just what she liked; highly
esteeming miss taylors judgment, but directed chiefly by her own. the real evils, indeed, of emmas
situation were the power of having rather too much her own way, and a disposition to think a little
too well of herself; these were the disadvantages which threatened alloy to her many enjoyments. the
danger, however, was at present so unperceived, that they did not by any means rank as misfortunes
with her. sorrow camea gentle sorrowbut not at all in the shape of any disagreeable
consciousness.miss taylor married. it was miss taylors loss which first brought grief. it was on the
wedding-day of this beloved friend that emma first sat in mournful thought of any continuance. the
wedding over, and the bride-people gone, her father and herself were left to dine together, with no
prospect of a third to cheer a long evening. her father composed himself to sleep after dinner, as
usual, and she had then only to sit and think of what she had lost. the event had every promise of
happiness for her friend. mr. weston was a man of unexceptionable character, easy fortune, suitable
age, and pleasant manners; and there was some satisfaction in considering with what self-denying,
generous friendship she had always wished and promoted the match; but it was a black mornings work
for her. the want of miss taylor would be felt every hour of every day. she recalled her past
kindnessthe kindness, the affection of sixteen yearshow she had taught and how she had played with
her from five years oldhow she had devoted all her powers to attach and amuse her in healthand how
nursed her through the various illnesses of childhood. a large debt of gratitude was owing here; but
the intercourse of the last seven years, the equal footing and perfect unreserve which had soon
followed isabellas marriage, on their being left to each other, was yet a dearer, tenderer
recollection. she had been a friend and companion such as few possessed: intelligent, well-informed,
useful, gentle, knowing all the ways of the family, interested in all its concerns, and peculiarly
interested in herself, in every pleasure, every scheme of hersone to whom she could speak every
thought as it arose, and who had such an affection for her as could never find fault. how was she to
bear the change?it was true that her friend was going only half a mile from them; but emma was aware
that great must be the difference between a mrs. weston, only half a mile from them, and a miss
taylor in the house; and with all her advantages, natural and domestic, she was now in great danger
of suffering from intellectual solitude. she dearly loved her father, but he was no companion for
her. he could not meet her in conversation, rational or playful. the evil of the actual disparity in
their ages (and mr. woodhouse had not married early) was much increased by his constitution and
habits; for having been a valetudinarian all his life, without activity of mind or body, he was a
much older man in ways than in years; and though everywhere beloved for the friendliness of his
heart and his amiable temper, his talents could not have recommended him at any time. her sister,
though comparatively but little removed by matrimony, being settled in london, only sixteen miles
off, was much beyond her daily reach; and many a long october and november evening must be struggled
through at hartfield, before christmas brought the next visit from isabella and her husband, and
their little children, to fill the house, and give her pleasant society again. highbury, the large
and populous village, almost amounting to a town, to which hartfield, in spite of its separate lawn,
and shrubberies, and name, did really belong, afforded her no equals. the woodhouses were first in
consequence there. all looked up to them. she had many acquaintance in the place, for her father was
universally civil, but not one among them who could be accepted in lieu of miss taylor for even half
a day. it was a melancholy change; and emma could not but sigh over it, and wish for impossible
things, till her father awoke, and made it necessary to be cheerful. his spirits required support.
he was a nervous man, easily depressed; fond of every body that he was used to, and hating to part
with them; hating change of every kind. matrimony, as the origin of change, was always disagreeable;
and he was by no means yet reconciled to his own daughters marrying, nor could ever speak of her but
with compassion, though it had been entirely a match of affection, when he was now obliged to part
with miss taylor too; and from his habits of gentle selfishness, and of being never able to suppose
that other people could feel differently from himself, he was very much disposed to think miss
taylor had done as sad a thing for herself as for them, and would have been a great deal happier if
she had spent all the rest of her life at hartfield. emma smiled and chatted as cheerfully as she
could, to keep him from such thoughts; but when tea came, it was impossible for him not to say
exactly as he had said at dinner, poor miss taylor!i wish she were here again. what a pity it is
that mr. weston ever thought of her! i cannot agree with you, papa; you know i cannot. mr. weston is
such a good-humoured, pleasant, excellent man, that he thoroughly deserves a good wife;and you would
not have had miss taylor live with us for ever, and bear all my odd humours, when she might have a
house of her own? a house of her own!but where is the advantage of a house of her own? this is three
times as large.and you have never any odd humours, my dear. how often we shall be going to see them,
and they coming to see us!we shall be always meeting! we must begin; we must go and pay wedding
visit very soon. my dear, how am i to get so far? randalls is such a distance. i could not walk half
so far. no, papa, nobody thought of your walking. we must go in the carriage, to be sure. the
carriage! but james will not like to put the horses to for such a little way;and where are the poor
horses to be while we are paying our visit? they are to be put into mr. westons stable, papa. you
know we have settled all that already. we talked it all over with mr. weston last night. and as for
james, you may be very sure he will always like going to randalls, because of his daughters being
housemaid there. i only doubt whether he will ever take us anywhere else. that was your doing, papa.
you got hannah that good place. nobody thought of hannah till you mentioned herjames is so obliged
to you! i am very glad i did think of her. it was very lucky, for i would not have had poor james
think himself slighted upon any account; and i am sure she will make a very good servant: she is a
civil, pretty-spoken girl; i have a great opinion of her. whenever i see her, she always curtseys
and asks me how i do, in a very pretty manner; and when you have had her here to do needlework, i
observe she always turns the lock of the door the right way and never bangs it. i am sure she will
be an excellent servant; and it will be a great comfort to poor miss taylor to have somebody about
her that she is used to see. whenever james goes over to see his daughter, you know, she will be
hearing of us. he will be able to tell her how we all are. emma spared no exertions to maintain this
happier flow of ideas, and hoped, by the help of backgammon, to get her father tolerably through the
evening, and be attacked by no regrets but her own. the backgammon-table was placed; but a visitor
immediately afterwards walked in and made it unnecessary. mr. knightley, a sensible man about seven
or eight-and-thirty, was not only a very old and intimate friend of the family, but particularly
connected with it, as the elder brother of isabellas husband. he lived about a mile from highbury,
was a frequent visitor, and always welcome, and at this time more welcome than usual, as coming
directly from their mutual connexions in london. he had returned to a late dinner, after some days
absence, and now walked up to hartfield to say that all were well in brunswick square. it was a
happy circumstance, and animated mr. woodhouse for some time. mr. knightley had a cheerful manner,
which always did him good; and his many inquiries after poor isabella and her children were answered
most satisfactorily. when this was over, mr. woodhouse gratefully observed, it is very kind of you,
mr. knightley, to come out at this late hour to call upon us. i am afraid you must have had a
shocking walk. not at all, sir. it is a beautiful moonlight night; and so mild that i must draw back
from your great fire. but you must have found it very damp and dirty. i wish you may not catch cold.
dirty, sir! look at my shoes. not a speck on them. well! that is quite surprising, for we have had a
vast deal of rain here. it rained dreadfully hard for half an hour while we were at breakfast. i
wanted them to put off the wedding. by the byei have not wished you joy. being pretty well aware of
what sort of joy you must both be feeling, i have been in no hurry with my congratulations; but i
hope it all went off tolerably well. how did you all behave? who cried most? ah! poor miss taylor!
tis a sad business. poor mr. and miss woodhouse, if you please; but i cannot possibly say poor miss
taylor. i have a great regard for you and emma; but when it comes to the question of dependence or
independence!at any rate, it must be better to have only one to please than two. especially when one
of those two is such a fanciful, troublesome creature! said emma playfully. that is what you have in
your head, i knowand what you would certainly say if my father were not by. i believe it is very
true, my dear, indeed, said mr. woodhouse, with a sigh. i am afraid i am sometimes very fanciful and
troublesome. my dearest papa! you do not think i could mean you, or suppose mr. knightley to mean
you. what a horrible idea! oh no! i meant only myself. mr. knightley loves to find fault with me,
you knowin a jokeit is all a joke. we always say what we like to one another. mr. knightley, in
fact, was one of the few people who could see faults in emma woodhouse, and the only one who ever
told her of them: and though this was not particularly agreeable to emma herself, she knew it would
be so much less so to her father, that she would not have him really suspect such a circumstance as
her not being thought perfect by every body. emma knows i never flatter her, said mr. knightley, but
i meant no reflection on any body. miss taylor has been used to have two persons to please; she will
now have but one. the chances are that she must be a gainer. well, said emma, willing to let it
passyou want to hear about the wedding; and i shall be happy to tell you, for we all behaved
charmingly. every body was punctual, every body in their best looks: not a tear, and hardly a long
face to be seen. oh no; we all felt that we were going to be only half a mile apart, and were sure
of meeting every day. dear emma bears every thing so well, said her father. but, mr. knightley, she
is really very sorry to lose poor miss taylor, and i am sure she will miss her more than she thinks
for. emma turned away her head, divided between tears and smiles. it is impossible that emma should
not miss such a companion, said mr. knightley. we should not like her so well as we do, sir, if we
could suppose it; but she knows how much the marriage is to miss taylors advantage; she knows how
very acceptable it must be, at miss taylors time of life, to be settled in a home of her own, and
how important to her to be secure of a comfortable provision, and therefore cannot allow herself to
feel so much pain as pleasure. every friend of miss taylor must be glad to have her so happily
married. and you have forgotten one matter of joy to me, said emma, and a very considerable onethat
i made the match myself. i made the match, you know, four years ago; and to have it take place, and
be proved in the right, when so many people said mr. weston would never marry again, may comfort me
for any thing. mr. knightley shook his head at her. her father fondly replied, ah! my dear, i wish
you would not make matches and foretell things, for whatever you say always comes to pass. pray do
not make any more matches. i promise you to make none for myself, papa; but i must, indeed, for
other people. it is the greatest amusement in the world! and after such success, you know!every body
said that mr. weston would never marry again. oh dear, no! mr. weston, who had been a widower so
long, and who seemed so perfectly comfortable without a wife, so constantly occupied either in his
business in town or among his friends here, always acceptable wherever he went, always cheerfulmr.
weston need not spend a single evening in the year alone if he did not like it. oh no! mr. weston
certainly would never marry again. some people even talked of a promise to his wife on her deathbed,
and others of the son and the uncle not letting him. all manner of solemn nonsense was talked on the
subject, but i believed none of it. ever since the dayabout four years agothat miss taylor and i met
with him in broadway lane, when, because it began to drizzle, he darted away with so much gallantry,
and borrowed two umbrellas for us from farmer mitchells, i made up my mind on the subject. i planned
the match from that hour; and when such success has blessed me in this instance, dear papa, you
cannot think that i shall leave off match-making. i do not understand what you mean by success, said
mr. knightley. success supposes endeavour. your time has been properly and delicately spent, if you
have been endeavouring for the last four years to bring about this marriage. a worthy employment for
a young ladys mind! but if, which i rather imagine, your making the match, as you call it, means
only your planning it, your saying to yourself one idle day, i think it would be a very good thing
for miss taylor if mr. weston were to marry her, and saying it again to yourself every now and then
afterwards, why do you talk of success? where is your merit? what are you proud of? you made a lucky
guess; and that is all that can be said. and have you never known the pleasure and triumph of a
lucky guess?i pity you.i thought you clevererfor, depend upon it a lucky guess is never merely luck.
there is always some talent in it. and as to my poor word success, which you quarrel with, i do not
know that i am so entirely without any claim to it. you have drawn two pretty pictures; but i think
there may be a thirda something between the do-nothing and the do-all. if i had not promoted mr.
westons visits here, and given many little encouragements, and smoothed many little matters, it
might not have come to any thing after all. i think you must know hartfield enough to comprehend
that. a straightforward, open-hearted man like weston, and a rational, unaffected woman like miss
taylor, may be safely left to manage their own concerns. you are more likely to have done harm to
yourself, than good to them, by interference. emma never thinks of herself, if she can do good to
others, rejoined mr. woodhouse, understanding but in part. but, my dear, pray do not make any more
matches; they are silly things, and break up ones family circle grievously. only one more, papa;
only for mr. elton. poor mr. elton! you like mr. elton, papa,i must look about for a wife for him.
there is nobody in highbury who deserves himand he has been here a whole year, and has fitted up his
house so comfortably, that it would be a shame to have him single any longerand i thought when he
was joining their hands to-day, he looked so very much as if he would like to have the same kind
office done for him! i think very well of mr. elton, and this is the only way i have of doing him a
service. mr. elton is a very pretty young man, to be sure, and a very good young man, and i have a
great regard for him. but if you want to shew him any attention, my dear, ask him to come and dine
with us some day. that will be a much better thing. i dare say mr. knightley will be so kind as to
meet him. with a great deal of pleasure, sir, at any time, said mr. knightley, laughing, and i agree
with you entirely, that it will be a much better thing. invite him to dinner, emma, and help him to
the best of the fish and the chicken, but leave him to chuse his own wife. depend upon it, a man of
six or seven-and-twenty can take care of himself. mr. weston was a native of highbury, and born of a
respectable family, which for the last two or three generations had been rising into gentility and
property. he had received a good education, but, on succeeding early in life to a small
independence, had become indisposed for any of the more homely pursuits in which his brothers were
engaged, and had satisfied an active, cheerful mind and social temper by entering into the militia
of his county, then embodied. captain weston was a general favourite; and when the chances of his
military life had introduced him to miss churchill, of a great yorkshire family, and miss churchill
fell in love with him, nobody was surprized, except her brother and his wife, who had never seen
him, and who were full of pride and importance, which the connexion would offend. miss churchill,
however, being of age, and with the full command of her fortunethough her fortune bore no proportion
to the family-estatewas not to be dissuaded from the marriage, and it took place, to the infinite
mortification of mr. and mrs. churchill, who threw her off with due decorum. it was an unsuitable
connexion, and did not produce much happiness. mrs. weston ought to have found more in it, for she
had a husband whose warm heart and sweet temper made him think every thing due to her in return for
the great goodness of being in love with him; but though she had one sort of spirit, she had not the
best. she had resolution enough to pursue her own will in spite of her brother, but not enough to
refrain from unreasonable regrets at that brothers unreasonable anger, nor from missing the luxuries
of her former home. they lived beyond their income, but still it was nothing in comparison of
enscombe: she did not cease to love her husband, but she wanted at once to be the wife of captain
weston, and miss churchill of enscombe. captain weston, who had been considered, especially by the
churchills, as making such an amazing match, was proved to have much the worst of the bargain; for
when his wife died, after a three years marriage, he was rather a poorer man than at first, and with
a child to maintain. from the expense of the child, however, he was soon relieved. the boy had, with
the additional softening claim of a lingering illness of his mothers, been the means of a sort of

Preprocessing example on MacBeth

In [60]:
imp_det = ImpostorDetector()
# sample_text = ds_gutenberg['pair'].iloc[0][0]
sys.path.append(os.path.abspath(".."))

with open(
    Path(os.getcwd()).resolve().parent
    / Path(CONFIG.PATH2GUTENBERG).parent
    / "Macbeth_William_Shakespeare.txt",
    "r",
) as f:
    sample_text = f.read()
print(textwrap.fill(sample_text, width=80))

ACT I  SCENE I. An open Place.    Thunder and Lightning. Enter three Witches.
FIRST WITCH. When shall we three meet again? In thunder, lightning, or in rain?
SECOND WITCH. When the hurlyburly’s done, When the battle’s lost and won.  THIRD
WITCH. That will be ere the set of sun.  FIRST WITCH. Where the place?  SECOND
WITCH. Upon the heath.  THIRD WITCH. There to meet with Macbeth.  FIRST WITCH. I
come, Graymalkin!  SECOND WITCH. Paddock calls.  THIRD WITCH. Anon.  ALL. Fair
is foul, and foul is fair: Hover through the fog and filthy air.   [_Exeunt._]
SCENE II. A Camp near Forres.   Alarum within. Enter King Duncan, Malcolm,
Donalbain, Lennox, with  Attendants, meeting a bleeding Captain.  DUNCAN. What
bloody man is that? He can report, As seemeth by his plight, of the revolt The
newest state.  MALCOLM. This is the sergeant Who, like a good and hardy soldier,
fought ’Gainst my captivity.—Hail, brave friend! Say to the King the knowledge
of the broil As thou didst leave it.  SOLDIER. Doubtful it stood; As two spent
swimmers that do cling together And choke their art. The merciless Macdonwald
(Worthy to be a rebel, for to that The multiplying villainies of nature Do swarm
upon him) from the Western Isles Of kerns and gallowglasses is supplied; And
Fortune, on his damned quarrel smiling, Show’d like a rebel’s whore. But all’s
too weak; For brave Macbeth (well he deserves that name), Disdaining Fortune,
with his brandish’d steel, Which smok’d with bloody execution, Like Valour’s
minion, carv’d out his passage, Till he fac’d the slave; Which ne’er shook
hands, nor bade farewell to him, Till he unseam’d him from the nave to the
chops, And fix’d his head upon our battlements.  DUNCAN. O valiant cousin!
worthy gentleman!  SOLDIER. As whence the sun ’gins his reflection Shipwracking
storms and direful thunders break, So from that spring, whence comfort seem’d to
come Discomfort swells. Mark, King of Scotland, mark: No sooner justice had,
with valour arm’d, Compell’d these skipping kerns to trust their heels, But the
Norweyan lord, surveying vantage, With furbish’d arms and new supplies of men,
Began a fresh assault.  DUNCAN. Dismay’d not this Our captains, Macbeth and
Banquo?  SOLDIER. Yes; As sparrows eagles, or the hare the lion. If I say sooth,
I must report they were As cannons overcharg’d with double cracks; So they
Doubly redoubled strokes upon the foe: Except they meant to bathe in reeking
wounds, Or memorize another Golgotha, I cannot tell— But I am faint, my gashes
cry for help.  DUNCAN. So well thy words become thee as thy wounds: They smack
of honour both.—Go, get him surgeons.   [_Exit Captain, attended._]   Enter Ross
and Angus.  Who comes here?  MALCOLM. The worthy Thane of Ross.  LENNOX. What a
haste looks through his eyes! So should he look That seems to speak things
strange.  ROSS. God save the King!  DUNCAN. Whence cam’st thou, worthy thane?
ROSS. From Fife, great King, Where the Norweyan banners flout the sky And fan
our people cold. Norway himself, with terrible numbers, Assisted by that most
disloyal traitor, The Thane of Cawdor, began a dismal conflict; Till that
Bellona’s bridegroom, lapp’d in proof, Confronted him with self-comparisons,
Point against point, rebellious arm ’gainst arm, Curbing his lavish spirit: and,
to conclude, The victory fell on us.  DUNCAN. Great happiness!  ROSS. That now
Sweno, the Norways’ king, craves composition; Nor would we deign him burial of
his men Till he disbursed at Saint Colme’s Inch Ten thousand dollars to our
general use.  DUNCAN. No more that Thane of Cawdor shall deceive Our bosom
interest. Go pronounce his present death, And with his former title greet
Macbeth.  ROSS. I’ll see it done.  DUNCAN. What he hath lost, noble Macbeth hath
won.   [_Exeunt._]  SCENE III. A heath.   Thunder. Enter the three Witches.
FIRST WITCH. Where hast thou been, sister?  SECOND WITCH. Killing swine.  THIRD
WITCH. Sister, where thou?  FIRST WITCH. A sailor’s wife had chestnuts in her
lap, And mounch’d, and mounch’d, and mounch’d. “Give me,” quoth I. “Aroint thee,
witch!” the rump-fed ronyon cries. Her husband’s to Aleppo gone, master o’ th’
_Tiger:_ But in a sieve I’ll thither sail, And, like a rat without a tail, I’ll
do, I’ll do, and I’ll do.  SECOND WITCH. I’ll give thee a wind.  FIRST WITCH.
Th’art kind.  THIRD WITCH. And I another.  FIRST WITCH. I myself have all the
other, And the very ports they blow, All the quarters that they know I’ the
shipman’s card. I will drain him dry as hay: Sleep shall neither night nor day
Hang upon his pent-house lid; He shall live a man forbid. Weary sev’n-nights
nine times nine, Shall he dwindle, peak, and pine: Though his bark cannot be
lost, Yet it shall be tempest-tost. Look what I have.  SECOND WITCH. Show me,
show me.  FIRST WITCH. Here I have a pilot’s thumb, Wrack’d as homeward he did
come.   [_Drum within._]  THIRD WITCH. A drum, a drum! Macbeth doth come.  ALL.
The Weird Sisters, hand in hand, Posters of the sea and land, Thus do go about,
about: Thrice to thine, and thrice to mine, And thrice again, to make up nine.
Peace!—the charm’s wound up.   Enter Macbeth and Banquo.  MACBETH. So foul and
fair a day I have not seen.  BANQUO. How far is’t call’d to Forres?—What are
these, So wither’d, and so wild in their attire, That look not like the
inhabitants o’ th’ earth, And yet are on’t?—Live you? or are you aught That man
may question? You seem to understand me, By each at once her choppy finger
laying Upon her skinny lips. You should be women, And yet your beards forbid me
to interpret That you are so.  MACBETH. Speak, if you can;—what are you?  FIRST
WITCH. All hail, Macbeth! hail to thee, Thane of Glamis!  SECOND WITCH. All
hail, Macbeth! hail to thee, Thane of Cawdor!  THIRD WITCH. All hail, Macbeth!
that shalt be king hereafter!  BANQUO. Good sir, why do you start and seem to
fear Things that do sound so fair?—I’ th’ name of truth, Are ye fantastical, or
that indeed Which outwardly ye show? My noble partner You greet with present
grace and great prediction Of noble having and of royal hope, That he seems rapt
withal. To me you speak not. If you can look into the seeds of time, And say
which grain will grow, and which will not, Speak then to me, who neither beg nor
fear Your favours nor your hate.  FIRST WITCH. Hail!  SECOND WITCH. Hail!  THIRD
WITCH. Hail!  FIRST WITCH. Lesser than Macbeth, and greater.  SECOND WITCH. Not
so happy, yet much happier.  THIRD WITCH. Thou shalt get kings, though thou be
none: So all hail, Macbeth and Banquo!  FIRST WITCH. Banquo and Macbeth, all
hail!  MACBETH. Stay, you imperfect speakers, tell me more. By Sinel’s death I
know I am Thane of Glamis; But how of Cawdor? The Thane of Cawdor lives, A
prosperous gentleman; and to be king Stands not within the prospect of belief,
No more than to be Cawdor. Say from whence You owe this strange intelligence? or
why Upon this blasted heath you stop our way With such prophetic
greeting?—Speak, I charge you.   [_Witches vanish._]  BANQUO. The earth hath
bubbles, as the water has, And these are of them. Whither are they vanish’d?
MACBETH. Into the air; and what seem’d corporal, Melted as breath into the wind.
Would they had stay’d!  BANQUO. Were such things here as we do speak about? Or
have we eaten on the insane root That takes the reason prisoner?  MACBETH. Your
children shall be kings.  BANQUO. You shall be king.  MACBETH. And Thane of
Cawdor too; went it not so?  BANQUO. To the selfsame tune and words. Who’s here?
Enter Ross and Angus.  ROSS. The King hath happily receiv’d, Macbeth, The news
of thy success, and when he reads Thy personal venture in the rebels’ fight, His
wonders and his praises do contend Which should be thine or his: silenc’d with
that, In viewing o’er the rest o’ th’ selfsame day, He finds thee in the stout
Norweyan ranks, Nothing afeard of what thyself didst make, Strange images of
death. As thick as tale Came post with post; and everyone did bear Thy praises
in his kingdom’s great defence, And pour’d them down before him.  ANGUS. We are
sent To give thee from our royal master thanks; Only to herald thee into his
sight, Not pay thee.  ROSS. And, for an earnest of a greater honour, He bade me,
from him, call thee Thane of Cawdor: In which addition, hail, most worthy thane,
For it is thine.  BANQUO. What, can the devil speak true?  MACBETH. The Thane of
Cawdor lives: why do you dress me In borrow’d robes?  ANGUS. Who was the Thane
lives yet, But under heavy judgement bears that life Which he deserves to lose.
Whether he was combin’d With those of Norway, or did line the rebel With hidden
help and vantage, or that with both He labour’d in his country’s wrack, I know
not; But treasons capital, confess’d and prov’d, Have overthrown him.  MACBETH.
[_Aside._] Glamis, and Thane of Cawdor: The greatest is behind. [_To Ross and
Angus._] Thanks for your pains. [_To Banquo._] Do you not hope your children
shall be kings, When those that gave the Thane of Cawdor to me Promis’d no less
to them?  BANQUO. That, trusted home, Might yet enkindle you unto the crown,
Besides the Thane of Cawdor. But ’tis strange: And oftentimes to win us to our
harm, The instruments of darkness tell us truths; Win us with honest trifles, to
betray’s In deepest consequence.— Cousins, a word, I pray you.  MACBETH.
[_Aside._] Two truths are told, As happy prologues to the swelling act Of the
imperial theme.—I thank you, gentlemen.— [_Aside._] This supernatural soliciting
Cannot be ill; cannot be good. If ill, Why hath it given me earnest of success,
Commencing in a truth? I am Thane of Cawdor: If good, why do I yield to that
suggestion Whose horrid image doth unfix my hair, And make my seated heart knock
at my ribs, Against the use of nature? Present fears Are less than horrible
imaginings. My thought, whose murder yet is but fantastical, Shakes so my single
state of man That function is smother’d in surmise, And nothing is but what is
not.  BANQUO. Look, how our partner’s rapt.  MACBETH. [_Aside._] If chance will
have me king, why, chance may crown me Without my stir.  BANQUO. New honours
come upon him, Like our strange garments, cleave not to their mould But with the
aid of use.  MACBETH. [_Aside._] Come what come may, Time and the hour runs
through the roughest day.  BANQUO. Worthy Macbeth, we stay upon your leisure.
MACBETH. Give me your favour. My dull brain was wrought With things forgotten.
Kind gentlemen, your pains Are register’d where every day I turn The leaf to
read them.—Let us toward the King.— Think upon what hath chanc’d; and at more
time, The interim having weigh’d it, let us speak Our free hearts each to other.
BANQUO. Very gladly.  MACBETH. Till then, enough.—Come, friends.   [_Exeunt._]
SCENE IV. Forres. A Room in the Palace.   Flourish. Enter Duncan, Malcolm,
Donalbain, Lennox and Attendants.  DUNCAN. Is execution done on Cawdor? Are not
Those in commission yet return’d?  MALCOLM. My liege, They are not yet come
back. But I have spoke With one that saw him die, who did report, That very
frankly he confess’d his treasons, Implor’d your Highness’ pardon, and set forth
A deep repentance. Nothing in his life Became him like the leaving it; he died
As one that had been studied in his death, To throw away the dearest thing he
ow’d As ’twere a careless trifle.  DUNCAN. There’s no art To find the mind’s
construction in the face: He was a gentleman on whom I built An absolute trust.
Enter Macbeth, Banquo, Ross and Angus.  O worthiest cousin! The sin of my
ingratitude even now Was heavy on me. Thou art so far before, That swiftest wing
of recompense is slow To overtake thee. Would thou hadst less deserv’d; That the
proportion both of thanks and payment Might have been mine! only I have left to
say, More is thy due than more than all can pay.  MACBETH. The service and the
loyalty I owe, In doing it, pays itself. Your Highness’ part Is to receive our
duties: and our duties Are to your throne and state, children and servants;
Which do but what they should, by doing everything Safe toward your love and
honour.  DUNCAN. Welcome hither: I have begun to plant thee, and will labour To
make thee full of growing.—Noble Banquo, That hast no less deserv’d, nor must be
known No less to have done so, let me infold thee And hold thee to my heart.
BANQUO. There if I grow, The harvest is your own.  DUNCAN. My plenteous joys,
Wanton in fulness, seek to hide themselves In drops of sorrow.—Sons, kinsmen,
thanes, And you whose places are the nearest, know, We will establish our estate
upon Our eldest, Malcolm; whom we name hereafter The Prince of Cumberland: which
honour must Not unaccompanied invest him only, But signs of nobleness, like
stars, shall shine On all deservers.—From hence to Inverness, And bind us
further to you.  MACBETH. The rest is labour, which is not us’d for you: I’ll be
myself the harbinger, and make joyful The hearing of my wife with your approach;
So, humbly take my leave.  DUNCAN. My worthy Cawdor!  MACBETH. [_Aside._] The
Prince of Cumberland!—That is a step On which I must fall down, or else
o’erleap, For in my way it lies. Stars, hide your fires! Let not light see my
black and deep desires. The eye wink at the hand, yet let that be, Which the eye
fears, when it is done, to see.   [_Exit._]  DUNCAN. True, worthy Banquo! He is
full so valiant; And in his commendations I am fed. It is a banquet to me. Let’s
after him, Whose care is gone before to bid us welcome: It is a peerless
kinsman.   [_Flourish. Exeunt._]  SCENE V. Inverness. A Room in Macbeth’s
Castle.   Enter Lady Macbeth, reading a letter.  LADY MACBETH. “They met me in
the day of success; and I have learned by the perfect’st report they have more
in them than mortal knowledge. When I burned in desire to question them further,
they made themselves air, into which they vanished. Whiles I stood rapt in the
wonder of it, came missives from the King, who all-hailed me, ‘Thane of Cawdor’;
by which title, before, these Weird Sisters saluted me, and referred me to the
coming on of time, with ‘Hail, king that shalt be!’ This have I thought good to
deliver thee (my dearest partner of greatness) that thou might’st not lose the
dues of rejoicing, by being ignorant of what greatness is promis’d thee. Lay it
to thy heart, and farewell.”  Glamis thou art, and Cawdor; and shalt be What
thou art promis’d. Yet do I fear thy nature; It is too full o’ th’ milk of human
kindness To catch the nearest way. Thou wouldst be great; Art not without
ambition, but without The illness should attend it. What thou wouldst highly,
That wouldst thou holily; wouldst not play false, And yet wouldst wrongly win.
Thou’dst have, great Glamis, That which cries, “Thus thou must do,” if thou have
it; And that which rather thou dost fear to do, Than wishest should be undone.
Hie thee hither, That I may pour my spirits in thine ear, And chastise with the
valour of my tongue All that impedes thee from the golden round, Which fate and
metaphysical aid doth seem To have thee crown’d withal.   Enter a Messenger.
What is your tidings?  MESSENGER. The King comes here tonight.  LADY MACBETH.
Thou’rt mad to say it. Is not thy master with him? who, were’t so, Would have
inform’d for preparation.  MESSENGER. So please you, it is true. Our thane is
coming. One of my fellows had the speed of him, Who, almost dead for breath, had
scarcely more Than would make up his message.  LADY MACBETH. Give him tending.
He brings great news.   [_Exit Messenger._]  The raven himself is hoarse That
croaks the fatal entrance of Duncan Under my battlements. Come, you spirits That
tend on mortal thoughts, unsex me here, And fill me, from the crown to the toe,
top-full Of direst cruelty! make thick my blood, Stop up th’ access and passage
to remorse, That no compunctious visitings of nature Shake my fell purpose, nor
keep peace between Th’ effect and it! Come to my woman’s breasts, And take my
milk for gall, your murd’ring ministers, Wherever in your sightless substances
You wait on nature’s mischief! Come, thick night, And pall thee in the dunnest
smoke of hell That my keen knife see not the wound it makes, Nor heaven peep
through the blanket of the dark To cry, “Hold, hold!”   Enter Macbeth.  Great
Glamis, worthy Cawdor! Greater than both, by the all-hail hereafter! Thy letters
have transported me beyond This ignorant present, and I feel now The future in
the instant.  MACBETH. My dearest love, Duncan comes here tonight.  LADY
MACBETH. And when goes hence?  MACBETH. Tomorrow, as he purposes.  LADY MACBETH.
O, never Shall sun that morrow see! Your face, my thane, is as a book where men
May read strange matters. To beguile the time, Look like the time; bear welcome
in your eye, Your hand, your tongue: look like the innocent flower, But be the
serpent under’t. He that’s coming Must be provided for; and you shall put This
night’s great business into my dispatch; Which shall to all our nights and days
to come Give solely sovereign sway and masterdom.  MACBETH. We will speak
further.  LADY MACBETH. Only look up clear; To alter favour ever is to fear.
Leave all the rest to me.   [_Exeunt._]  SCENE VI. The same. Before the Castle.
Hautboys. Servants of Macbeth attending.   Enter Duncan, Malcolm, Donalbain,
Banquo, Lennox, Macduff, Ross, Angus  and Attendants.  DUNCAN. This castle hath
a pleasant seat. The air Nimbly and sweetly recommends itself Unto our gentle
senses.  BANQUO. This guest of summer, The temple-haunting martlet, does
approve, By his loved mansionry, that the heaven’s breath Smells wooingly here:
no jutty, frieze, Buttress, nor coign of vantage, but this bird hath made his
pendant bed and procreant cradle. Where they most breed and haunt, I have
observ’d The air is delicate.   Enter Lady Macbeth.  DUNCAN. See, see, our
honour’d hostess!— The love that follows us sometime is our trouble, Which still
we thank as love. Herein I teach you How you shall bid God ’ild us for your
pains, And thank us for your trouble.  LADY MACBETH. All our service, In every
point twice done, and then done double, Were poor and single business to contend
Against those honours deep and broad wherewith Your Majesty loads our house: for
those of old, And the late dignities heap’d up to them, We rest your hermits.
DUNCAN. Where’s the Thane of Cawdor? We cours’d him at the heels, and had a
purpose To be his purveyor: but he rides well; And his great love, sharp as his
spur, hath holp him To his home before us. Fair and noble hostess, We are your
guest tonight.  LADY MACBETH. Your servants ever Have theirs, themselves, and
what is theirs, in compt, To make their audit at your Highness’ pleasure, Still
to return your own.  DUNCAN. Give me your hand; Conduct me to mine host: we love
him highly, And shall continue our graces towards him. By your leave, hostess.
[_Exeunt._]  SCENE VII. The same. A Lobby in the Castle.   Hautboys and torches.
Enter, and pass over, a Sewer and divers  Servants with dishes and service. Then
enter Macbeth.  MACBETH. If it were done when ’tis done, then ’twere well It
were done quickly. If th’ assassination Could trammel up the consequence, and
catch With his surcease success; that but this blow Might be the be-all and the
end-all—here, But here, upon this bank and shoal of time, We’d jump the life to
come. But in these cases We still have judgement here; that we but teach Bloody
instructions, which being taught, return To plague th’ inventor. This even-
handed justice Commends th’ ingredience of our poison’d chalice To our own lips.
He’s here in double trust: First, as I am his kinsman and his subject, Strong
both against the deed; then, as his host, Who should against his murderer shut
the door, Not bear the knife myself. Besides, this Duncan Hath borne his
faculties so meek, hath been So clear in his great office, that his virtues Will
plead like angels, trumpet-tongued, against The deep damnation of his taking-

In [61]:
normalized_text = imp_det.preprocess_text(sample_text)
print(textwrap.fill(normalized_text, width=80))

an open place. thunder and lightning. enter three witches. when shall we three
meet again? in thunder, lightning, or in rain? when the hurlyburlys done, when
the battles lost and won. that will be ere the set of sun. where the place? upon
the heath. there to meet with macbeth. i come, graymalkin! paddock calls. anon.
fair is foul, and foul is fair: hover through the fog and filthy air. exeunt. a
camp near forres. alarum within. enter king duncan, malcolm, donalbain, lennox,
with attendants, meeting a bleeding captain. what bloody man is that? he can
report, as seemeth by his plight, of the revolt the newest state. this is the
sergeant who, like a good and hardy soldier, fought gainst my captivity.hail,
brave friend! say to the king the knowledge of the broil as thou didst leave it.
doubtful it stood; as two spent swimmers that do cling together and choke their
art. the merciless macdonwald (worthy to be a rebel, for to that the multiplying
villainies of nature do swarm upon him) from the western isles of kerns and
gallowglasses is supplied; and fortune, on his damned quarrel smiling, showd
like a rebels whore. but alls too weak; for brave macbeth (well he deserves that
name), disdaining fortune, with his brandishd steel, which smokd with bloody
execution, like valours minion, carvd out his passage, till he facd the slave;
which neer shook hands, nor bade farewell to him, till he unseamd him from the
nave to the chops, and fixd his head upon our battlements. o valiant cousin!
worthy gentleman! as whence the sun gins his reflection shipwracking storms and
direful thunders break, so from that spring, whence comfort seemd to come
discomfort swells. mark, king of scotland, mark: no sooner justice had, with
valour armd, compelld these skipping kerns to trust their heels, but the
norweyan lord, surveying vantage, with furbishd arms and new supplies of men,
began a fresh assault. dismayd not this our captains, macbeth and banquo? yes;
as sparrows eagles, or the hare the lion. if i say sooth, i must report they
were as cannons overchargd with double cracks; so they doubly redoubled strokes
upon the foe: except they meant to bathe in reeking wounds, or memorize another
golgotha, i cannot tell but i am faint, my gashes cry for help. so well thy
words become thee as thy wounds: they smack of honour both.go, get him surgeons.
exit captain, attended. enter ross and angus. who comes here? the worthy thane
of ross. what a haste looks through his eyes! so should he look that seems to
speak things strange. god save the king! whence camst thou, worthy thane? from
fife, great king, where the norweyan banners flout the sky and fan our people
cold. norway himself, with terrible numbers, assisted by that most disloyal
traitor, the thane of cawdor, began a dismal conflict; till that bellonas
bridegroom, lappd in proof, confronted him with self-comparisons, point against
point, rebellious arm gainst arm, curbing his lavish spirit: and, to conclude,
the victory fell on us. great happiness! that now sweno, the norways king,
craves composition; nor would we deign him burial of his men till he disbursed
at saint colmes inch ten thousand dollars to our general use. no more that thane
of cawdor shall deceive our bosom interest. go pronounce his present death, and
with his former title greet macbeth. ill see it done. what he hath lost, noble
macbeth hath won. exeunt. a heath. thunder. enter the three witches. where hast
thou been, sister? killing swine. sister, where thou? a sailors wife had
chestnuts in her lap, and mounchd, and mounchd, and mounchd. give me, quoth i.
aroint thee, witch! the rump-fed ronyon cries. her husbands to aleppo gone,
master o th tiger: but in a sieve ill thither sail, and, like a rat without a
tail, ill do, ill do, and ill do. ill give thee a wind. thart kind. and i
another. i myself have all the other, and the very ports they blow, all the
quarters that they know i the shipmans card. i will drain him dry as hay: sleep
shall neither night nor day hang upon his pent-house lid; he shall live a man
forbid. weary sevn-nights nine times nine, shall he dwindle, peak, and pine:
though his bark cannot be lost, yet it shall be tempest-tost. look what i have.
show me, show me. here i have a pilots thumb, wrackd as homeward he did come.
drum within. a drum, a drum! macbeth doth come. the weird sisters, hand in hand,
posters of the sea and land, thus do go about, about: thrice to thine, and
thrice to mine, and thrice again, to make up nine. peace!the charms wound up.
enter macbeth and banquo. so foul and fair a day i have not seen. how far ist
calld to forres?what are these, so witherd, and so wild in their attire, that
look not like the inhabitants o th earth, and yet are ont?live you? or are you
aught that man may question? you seem to understand me, by each at once her
choppy finger laying upon her skinny lips. you should be women, and yet your
beards forbid me to interpret that you are so. speak, if you can;what are you?
all hail, macbeth! hail to thee, thane of glamis! all hail, macbeth! hail to
thee, thane of cawdor! all hail, macbeth! that shalt be king hereafter! good
sir, why do you start and seem to fear things that do sound so fair?i th name of
truth, are ye fantastical, or that indeed which outwardly ye show? my noble
partner you greet with present grace and great prediction of noble having and of
royal hope, that he seems rapt withal. to me you speak not. if you can look into
the seeds of time, and say which grain will grow, and which will not, speak then
to me, who neither beg nor fear your favours nor your hate. hail! hail! hail!
lesser than macbeth, and greater. not so happy, yet much happier. thou shalt get
kings, though thou be none: so all hail, macbeth and banquo! banquo and macbeth,
all hail! stay, you imperfect speakers, tell me more. by sinels death i know i
am thane of glamis; but how of cawdor? the thane of cawdor lives, a prosperous
gentleman; and to be king stands not within the prospect of belief, no more than
to be cawdor. say from whence you owe this strange intelligence? or why upon
this blasted heath you stop our way with such prophetic greeting?speak, i charge
you. witches vanish. the earth hath bubbles, as the water has, and these are of
them. whither are they vanishd? into the air; and what seemd corporal, melted as
breath into the wind. would they had stayd! were such things here as we do speak
about? or have we eaten on the insane root that takes the reason prisoner? your
children shall be kings. you shall be king. and thane of cawdor too; went it not
so? to the selfsame tune and words. whos here? enter ross and angus. the king
hath happily receivd, macbeth, the news of thy success, and when he reads thy
personal venture in the rebels fight, his wonders and his praises do contend
which should be thine or his: silencd with that, in viewing oer the rest o th
selfsame day, he finds thee in the stout norweyan ranks, nothing afeard of what
thyself didst make, strange images of death. as thick as tale came post with
post; and everyone did bear thy praises in his kingdoms great defence, and pourd
them down before him. we are sent to give thee from our royal master thanks;
only to herald thee into his sight, not pay thee. and, for an earnest of a
greater honour, he bade me, from him, call thee thane of cawdor: in which
addition, hail, most worthy thane, for it is thine. what, can the devil speak
true? the thane of cawdor lives: why do you dress me in borrowd robes? who was
the thane lives yet, but under heavy judgement bears that life which he deserves
to lose. whether he was combind with those of norway, or did line the rebel with
hidden help and vantage, or that with both he labourd in his countrys wrack, i
know not; but treasons capital, confessd and provd, have overthrown him. aside.
glamis, and thane of cawdor: the greatest is behind. to ross and angus. thanks
for your pains. to banquo. do you not hope your children shall be kings, when
those that gave the thane of cawdor to me promisd no less to them? that, trusted
home, might yet enkindle you unto the crown, besides the thane of cawdor. but
tis strange: and oftentimes to win us to our harm, the instruments of darkness
tell us truths; win us with honest trifles, to betrays in deepest consequence.
cousins, a word, i pray you. aside. two truths are told, as happy prologues to
the swelling the imperial theme.i thank you, gentlemen. aside. this supernatural
soliciting cannot be ill; cannot be good. if ill, why hath it given me earnest
of success, commencing in a truth? i am thane of cawdor: if good, why do i yield
to that suggestion whose horrid image doth unfix my hair, and make my seated
heart knock at my ribs, against the use of nature? present fears are less than
horrible imaginings. my thought, whose murder yet is but fantastical, shakes so
my single state of man that function is smotherd in surmise, and nothing is but
what is not. look, how our partners rapt. aside. if chance will have me king,
why, chance may crown me without my stir. new honours come upon him, like our
strange garments, cleave not to their mould but with the aid of use. aside. come
what come may, time and the hour runs through the roughest day. worthy macbeth,
we stay upon your leisure. give me your favour. my dull brain was wrought with
things forgotten. kind gentlemen, your pains are registerd where every day i
turn the leaf to read them.let us toward the king. think upon what hath chancd;
and at more time, the interim having weighd it, let us speak our free hearts
each to other. very gladly. till then, enough.come, friends. exeunt. forres. a
room in the palace. flourish. enter duncan, malcolm, donalbain, lennox and
attendants. is execution done on cawdor? are not those in commission yet
returnd? my liege, they are not yet come back. but i have spoke with one that
saw him die, who did report, that very frankly he confessd his treasons, implord
your highness pardon, and set forth a deep repentance. nothing in his life
became him like the leaving it; he died as one that had been studied in his
death, to throw away the dearest thing he owd as twere a careless trifle. theres
no art to find the minds construction in the face: he was a gentleman on whom i
built an absolute trust. enter macbeth, banquo, ross and angus. o worthiest
cousin! the sin of my ingratitude even now was heavy on me. thou art so far
before, that swiftest wing of recompense is slow to overtake thee. would thou
hadst less deservd; that the proportion both of thanks and payment might have
been mine! only i have left to say, more is thy due than more than all can pay.
the service and the loyalty i owe, in doing it, pays itself. your highness part
is to receive our duties: and our duties are to your throne and state, children
and servants; which do but what they should, by doing everything safe toward
your love and honour. welcome hither: i have begun to plant thee, and will
labour to make thee full of growing.noble banquo, that hast no less deservd, nor
must be known no less to have done so, let me infold thee and hold thee to my
heart. there if i grow, the harvest is your own. my plenteous joys, wanton in
fulness, seek to hide themselves in drops of sorrow.sons, kinsmen, thanes, and
you whose places are the nearest, know, we will establish our estate upon our
eldest, malcolm; whom we name hereafter the prince of cumberland: which honour
must not unaccompanied invest him only, but signs of nobleness, like stars,
shall shine on all deservers.from hence to inverness, and bind us further to
you. the rest is labour, which is not usd for you: ill be myself the harbinger,
and make joyful the hearing of my wife with your approach; so, humbly take my
leave. my worthy cawdor! aside. the prince of cumberland!that is a step on which
i must fall down, or else oerleap, for in my way it lies. stars, hide your
fires! let not light see my black and deep desires. the eye wink at the hand,
yet let that be, which the eye fears, when it is done, to see. exit. true,
worthy banquo! he is full so valiant; and in his commendations i am fed. it is a
banquet to me. lets after him, whose care is gone before to bid us welcome: it
is a peerless kinsman. flourish. exeunt. inverness. a room in macbeths castle.
enter lady macbeth, reading a letter. they met me in the day of success; and i
have learned by the perfectst report they have more in them than mortal
knowledge. when i burned in desire to question them further, they made
themselves air, into which they vanished. whiles i stood rapt in the wonder of
it, came missives from the king, who all-hailed me, thane of cawdor; by which
title, before, these weird sisters saluted me, and referred me to the coming on
of time, with hail, king that shalt be! this have i thought good to deliver thee
(my dearest partner of greatness) that thou mightst not lose the dues of
rejoicing, by being ignorant of what greatness is promisd thee. lay it to thy
heart, and farewell. glamis thou art, and cawdor; and shalt be what thou art
promisd. yet do i fear thy nature; it is too full o th milk of human kindness to
catch the nearest way. thou wouldst be great; art not without ambition, but
without the illness should attend it. what thou wouldst highly, that wouldst
thou holily; wouldst not play false, and yet wouldst wrongly win. thoudst have,
great glamis, that which cries, thus thou must do, if thou have it; and that
which rather thou dost fear to do, than wishest should be undone. hie thee
hither, that i may pour my spirits in thine ear, and chastise with the valour of
my tongue all that impedes thee from the golden round, which fate and
metaphysical aid doth seem to have thee crownd withal. enter a messenger. what
is your tidings? the king comes here tonight. thourt mad to say it. is not thy
master with him? who, weret so, would have informd for preparation. so please
you, it is true. our thane is coming. one of my fellows had the speed of him,
who, almost dead for breath, had scarcely more than would make up his message.
give him tending. he brings great news. exit messenger. the raven himself is
hoarse that croaks the fatal entrance of duncan under my battlements. come, you
spirits that tend on mortal thoughts, unsex me here, and fill me, from the crown
to the toe, top-full of direst cruelty! make thick my blood, stop up th access
and passage to remorse, that no compunctious visitings of nature shake my fell
purpose, nor keep peace between th effect and it! come to my womans breasts, and
take my milk for gall, your murdring ministers, wherever in your sightless
substances you wait on natures mischief! come, thick night, and pall thee in the
dunnest smoke of hell that my keen knife see not the wound it makes, nor heaven
peep through the blanket of the dark to cry, hold, hold! enter macbeth. great
glamis, worthy cawdor! greater than both, by the all-hail hereafter! thy letters
have transported me beyond this ignorant present, and i feel now the future in
the instant. my dearest love, duncan comes here tonight. and when goes hence?
tomorrow, as he purposes. o, never shall sun that morrow see! your face, my
thane, is as a book where men may read strange matters. to beguile the time,
look like the time; bear welcome in your eye, your hand, your tongue: look like
the innocent flower, but be the serpent undert. he thats coming must be provided
for; and you shall put this nights great business into my dispatch; which shall
to all our nights and days to come give solely sovereign sway and masterdom. we
will speak further. only look up clear; to alter favour ever is to fear. leave
all the rest to me. exeunt. the same. before the castle. hautboys. servants of
macbeth attending. enter duncan, malcolm, donalbain, banquo, lennox, macduff,
ross, angus and attendants. this castle hath a pleasant seat. the air nimbly and
sweetly recommends itself unto our gentle senses. this guest of summer, the
temple-haunting martlet, does approve, by his loved mansionry, that the heavens
breath smells wooingly here: no jutty, frieze, buttress, nor coign of vantage,
but this bird hath made his pendant bed and procreant cradle. where they most
breed and haunt, i have observd the air is delicate. enter lady macbeth. see,
see, our honourd hostess! the love that follows us sometime is our trouble,
which still we thank as love. herein i teach you how you shall bid god ild us
for your pains, and thank us for your trouble. all our service, in every point
twice done, and then done double, were poor and single business to contend
against those honours deep and broad wherewith your majesty loads our house: for
those of old, and the late dignities heapd up to them, we rest your hermits.
wheres the thane of cawdor? we coursd him at the heels, and had a purpose to be
his purveyor: but he rides well; and his great love, sharp as his spur, hath
holp him to his home before us. fair and noble hostess, we are your guest
tonight. your servants ever have theirs, themselves, and what is theirs, in
compt, to make their audit at your highness pleasure, still to return your own.
give me your hand; conduct me to mine host: we love him highly, and shall
continue our graces towards him. by your leave, hostess. exeunt. the same. a
lobby in the castle. hautboys and torches. enter, and pass over, a sewer and
divers servants with dishes and service. then enter macbeth. if it were done
when tis done, then twere well it were done quickly. if th assassination could
trammel up the consequence, and catch with his surcease success; that but this
blow might be the be-all and the end-allhere, but here, upon this bank and shoal
of time, wed jump the life to come. but in these cases we still have judgement
here; that we but teach bloody instructions, which being taught, return to
plague th inventor. this even-handed justice commends th ingredience of our
poisond chalice to our own lips. hes here in double trust: first, as i am his
kinsman and his subject, strong both against the deed; then, as his host, who
should against his murderer shut the door, not bear the knife myself. besides,
this duncan hath borne his faculties so meek, hath been so clear in his great
office, that his virtues will plead like angels, trumpet-tongued, against the
deep damnation of his taking-off; and pity, like a naked new-born babe, striding
the blast, or heavens cherubin, horsd upon the sightless couriers of the air,
shall blow the horrid deed in every eye, that tears shall drown the wind.i have
no spur to prick the sides of my intent, but only vaulting ambition, which
oerleaps itself and falls on th other enter lady macbeth. how now! what news? he
has almost suppd. why have you left the chamber? hath he askd for me? know you
not he has? we will proceed no further in this business: he hath honourd me of
late; and i have bought golden opinions from all sorts of people, which would be
worn now in their newest gloss, not cast aside so soon. was the hope drunk
wherein you dressd yourself? hath it slept since? and wakes it now, to look so
green and pale at what it did so freely? from this time such i account thy love.
art thou afeard to be the same in thine own valour as thou art in desire?
wouldst thou have that which thou esteemst the ornament of life, and live a
coward in thine own esteem, letting i dare not wait upon i would, like the poor
cat i th adage? prythee, peace! i dare do all that may become a man; who dares
do more is none. what beast wast, then, that made you break this enterprise to
me? when you durst do it, then you were a man; and, to be more than what you
were, you would be so much more the man. nor time nor place did then adhere, and
yet you would make both: they have made themselves, and that their fitness now
does unmake you. i have given suck, and know how tender tis to love the babe
that milks me: i would, while it was smiling in my face, have pluckd my nipple

In [62]:
gutenberg_stats = gutenberg.dataset_stats()

In [63]:
# gutenberg.plot_avg_text_length_per_author()
# gutenberg.plot_text_length_histogram(bins=50)
# gutenberg.boxplots_text_len_ngrams()

# # Python garbage collector to release memory
# del gutenberg
# gc.collect()

## PAN 25

In [64]:
# pan25 = datasets.Pan25Visualization()
# pan25_stats = pan25.dataset_stats()

## Webis Koppel dataset

In [65]:
# koppel_webis = datasets.KoppelWebisVisualization()
# koppel_webis_stats = koppel_webis.dataset_stats()

In [66]:
# koppel_webis.plot_avg_text_length_per_author()
# koppel_webis.plot_text_length_histogram(bins=50)
# koppel_webis.boxplots_text_len_ngrams()

# # Python garbage collector to release memory
# del koppel_webis
# gc.collect()

## Compare datasets

In [67]:
combined_stats = pd.concat(
    [
        pan20_stats,
        blog_stats,
        gutenberg_stats,
        student_essays_stats,
        # pan23_stats, koppel_webis_stats, # pan25_stats
    ],
    axis=0,
    ignore_index=True,
)  # concat rows
combined_stats.set_index("dataset", inplace=True)  # set dataset as index
save_path = Path.cwd().parent / CONFIG.SAVE_PATH / "all_data" / "statistics"
save_path.mkdir(parents=True, exist_ok=True)  # create directory if it doesn't exist
timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
combined_stats.to_csv(
    save_path / f"combined_stats_{timestamp}.csv", float_format="%.2f"
)
print(f"Combined statistics saved to {save_path / f'combined_stats_{timestamp}.csv'}")

Combined statistics saved to /Users/klara/Developer/Uni/MA/artificial-authorship-verification/results/all_data/statistics/combined_stats_20250718_133227.csv

In [68]:
display(combined_stats)

,num_pairs,num_authors,num_same_pairs,num_different_pairs,avg_text_len_chars,min_text_len_chars,max_text_len_chars,std_text_len_chars,avg_text_len_words,min_text_len_words,max_text_len_words,std_text_len_words,median_text_len_words
dataset,,,,,,,,,,,,,
pan20,66906,52773,35616,31290,21418.64,5364,296734,2682.43,3914.74,505,55413,512.28,3889
blog,20547,9300,10889,9658,4603.75,1152,390632,5129.62,853.32,500,70374,937.24,673
gutenberg,12,7,6,6,437870.75,63938,1696684,387405.67,78698.79,11443,297704,68329.91,60282
student_essays,3952,588,221,3731,3404.76,2399,6930,665.39,651.63,500,1362,129.22,620